### ISSUE TITLE
Опции для девушек

### ISSUE THREAD

**Issue by Fenslau** [tebaly/freedomsex#100]
"мы не рассматриваем варианты инструментов позволяющие игнорировать"
Уже есть инстремент "заблокировать" - это тот же игнор. 

+ сделать для девушек возможность побыть вне сообщений какое то время - на видном месте, там же справа вверху, разместить опцию "не писать мне в течение хх минут" при этом сообщения просто будут игнориться.
+ сделать возможность отметить все сообщения как прочитанные, без блокировки анкет, если захочет, потом вернется к ним, лишь бы они не мелькали и не пикали.
если она закрыла всплывающее сообщение справа вверху, то больше от этого контакта сообщения всплывать не будут, пока она их не прочитает.
+ добавить для нее опцию по желанию: "отобразить сообщения только по моему профилю, остальные удалить/пометить как прочитанные, проигнорированные/...()

выбрать какой то вариант из одного.

Все это отображать при количестве сообщений новых, превышающих хх и отображать сверху от первого всплывающего сообщения.

**Comment by tebaly** [comment]
Спасибо 

> заблокировать

Да есть, его не может не быть. Но на этом наши инструменты как бы в общем то и всё :)

[![Аль](http://img.youtube.com/vi/LOw-xqTLBzE/0.jpg)](https://www.youtube.com/watch?v=LOw-xqTLBzE)
