### ISSUE TITLE
В реале списывается за каждое сообщение, даже одному и тому же контакту.

### ISSUE THREAD

**Issue by tebaly** [tebaly/freedomsex#101]
Не знаю, почему так. Но у моей тестовой анкеты списывали только за первый факт игнорирования параметра **1 кредитик**. Потом можно было писать тому же контакту неограниченное количество сообщений. Тогда как в реале списывается за каждое сообщение, даже одному и тому же контакту. Почему так, не могу понять.

**Comment by tebaly** [comment]
Если можно, давайте разберем подробнее. Вы втянули в стороннюю проблему ещё и кредиты
* Если у вас есть долг по капчам - то кредиты списываются пока долг не спишется
* Если долга нет, ничего не списывается при переписке с собеседником 

Это очень хорошо, что вы замечаете много деталей в работе системы безопасности. Мы крайне благодарны вам за участие в обсуждении проблем
* есть некоторые _скрытно_ работающие алгоритмы, понять которые сложно 
* работа таких алгоритмов делалась такой, чтобы её сложно было понять

**Comment by Fenslau** [comment]
Допустим долга по кредитам нет. И получается что я могу с новой анкеты общаться с кем-попало за 1 кредит (который списывается в момент написания сообщения) - это хорошо. Но почему тогда у моего основного аккаунта списываются кредиты за _каждое_ сообщение контакту, с которым я уже бох знает сколько общаюсь, но не вписываюсь в формат?

**Comment by Fenslau** [comment]
хотя может быть там учитываются ответы... Если мне ответили и я написал снова - то снова списываются кредиты. А если я пишу без ответа одному и тому же, то списывается один раз..

**Comment by Fenslau** [comment]
Предлагаю или списывать или не списывать: 
+ если мне все таки ответили - то больше не списывать, если идет нормальный диалог, списывать только вначале его.
+ списывать за _каждый_ промах - за город, возраст, вирт (что там еще) - сразу по факту нужное количество кредитов и в дальнейшем поступать как будет принято по п.1

**Comment by tebaly** [comment]
Не. Так не пойдёт :) Существует лимит, согласно которому наступает момент когда
* начинается ограничение общения по сайту целиком, вплоть до блокировки общения вовсе
* при этом уже не важно, когда и с кем вы общались ранее

**Comment by tebaly** [comment]
Этот лимит важен, его нельзя отключать
