### ISSUE TITLE
Зеленый кружочек слева от имени

### ISSUE THREAD

**Issue by Fenslau** [tebaly/freedomsex#102]
Уже давно становится причиной вопросов. Может быть ненавязчиво подсказочку выводить, при наведении на него мышью? Как например, когда наводим на "вирт" или @  в поиске анкет.

**Comment by tebaly** [comment]
Это воистину мифическая фитча :)

**Comment by Fenslau** [comment]
Ну пользователи то волнуются! Спрашивают Юлию, что он означает, другие сразу пишут, мол, что за беспредел, только что онлайн была, теперь уже нет )
А хотя, это спрашивают только парни, так что в принципе можно и не трогать. Короче на усмотрение ) 
Я вот сейчас подумал, что даже и лучше оставить. Как интересную фишку. Будут меньше писать одним и тем же. Короче задумка воистину клевая. Кто разобрался - молодец. А нет - так и не беда. Закрываем )

**Comment by Fenslau** [comment]
Идея суперская: Делаем зеленый кружок слева, который обозначает обычно что-то вроде "онлайн". Если его нет, то значит "оффлайн" типа. Защита от настойчивых, которые еще не разобрались в функционале этого зеленого кружка.
Супер.

**Comment by tebaly** [comment]
ПГС дивная вещь)) нет, такого смысла в него не закладывалось
* был эксперимент, по изучению "интуитивности" интерфейса
* поэтому никаких _хинтов_, подсказок и публикаций не делали

В целом значение
* эту анкету вы еще не посещали
* после посещения анкеты пропадет

Методом исключения
* в строке поиска есть элемент "онлайн", значит это не _онлайн_
