### ISSUE TITLE
В профиле пользователя, если хотим написать коммент

### ISSUE THREAD

**Issue by Fenslau** [tebaly/freedomsex#103]
В профиле пользователя, если хотим написать коммент и выбрать его из списка мы кликаем - разворачивается список !фэйк !спам и т.д. Так вот, если у него есть фотки, на которые жаловались, то эти фотки заслоняют собой нижние строчки этого списка удобного. и ничего не видно!

**Comment by tebaly** [comment]
Спасибо. Исправлено
