### ISSUE TITLE
Раскрытие IP адреса

### ISSUE THREAD

**Issue by mj4444ru** [tebaly/freedomsex#105]
А давайте в админке будем отображать последний IP адрес человека?
Ну так, чисто для поиска клонов...
А можно и прям в поиске в публичной части, если как админ зашёл... все клоны будут как на лодони...

Понятное дело конфидициальность и бла бла бла, по этому предлагаю отображать хеш, который даже при сливе алгоритма не даст реального адреса...

**Comment by Fenslau** [comment]
За. 
Хотел предложить что-то такое тоже, но почему то подумал, что не поддержат. Иногда бывает полезно. Конечно, сейчас время всяческих динамических ип на 3г и прочее, но тем не менее не помешает. А заодно рядом автоматически отображать и сам хост.

**Comment by mj4444ru** [comment]
$hash = [];
$c = 0;
$i1_start = 1; $i1_stop = 1;
$i2_start = 1; $i2_stop = 254;
$i3_start = 1; $i3_stop = 254;
$i4_start = 1; $i4_stop = 254;
for ($i1 = $i1_start; $i1 <= $i1_stop; $i1++) {
    for ($i2 = $i2_start; $i2 <= $i2_stop; $i2++) {
        for ($i3 = $i3_start; $i3 <= $i3_stop; $i3++) {
            for ($i4 = $i4_start; $i4 <= $i4_stop; $i4++) {
                $c++;
                $ip = "$i1.$i2.$i3.$i4";
                $h = crc32(substr(md5("$ip jfgniuwejhpawgjpawhgpgn"), 1, 5));
                if (isset($hash[$h])) {
                    $hash[$h]++;
                } else {
                    $hash[$h] = 1;
                }
            }
        }
    }
}
echo "Всего адресов: $c, уникальных хешей: ".count($hash);

Результат:
Всего адресов: 16387064, уникальных хешей: 1048573

**Comment by mj4444ru** [comment]
а хост зачем? чтобы позвонил другу и тебе сказали адрес пользователя?
сейчас всё пробивается за 5 минут у кого связи (деньги) есть...

**Comment by mj4444ru** [comment]
на меня как то местные горе хакеры дос атаку устроили... через час у меня был список адресов... пошёл перерезал провода... быстро и жёстко...

**Comment by Fenslau** [comment]
Ну да, часто бывает, в серое заходишь, девка пососать хочет, ну как тут без адреса )

**Comment by tebaly** [comment]
> сейчас всё пробивается за 5 минут у кого связи (деньги) есть...

Основная причина по которой адрес не публикуется

> по этому предлагаю отображать хеш, который даже при сливе алгоритма не даст реального адреса...

Очень здравая идея. Будьте автором, оформите новый тикет как "предлагаю отображать хеш IP адреса"

**Comment by mj4444ru** [comment]
Вы издеваетесь???

**Comment by tebaly** [comment]
Реальные IP светить нельзя - `конфидициальность и бла бла бла`

Реальные IP Нарушителей мы хотели публиковать по запросу в системе автоматически - и сделаем это. Выглядеть будет схоже с запросом на блокирование анкеты, только теперь администратор подает заявку на публикацию информации об обращениях к сервисам - IP адрес, время обращения. Запрос может быть отклонен другим администратором, если оснований недостаточно. Правила будут разработаны отдельным соглашением Сообщества. 

Такая информация может быть необходима при расследованиях правонарушений по обращениям граждан страны самостоятельно. Такой информации будет вполне достаточно для установления адреса Нарушитеся, во многих случаях. Без необходимости официальных обращений.

Есть ли на данный момент в этом (реальный IP адрес человека) острая потребность?

**Comment by tebaly** [comment]
> Вы издеваетесь???

Да нет. Каждой идее новый тикет(Issue) - зачем так эмоционально. Просто усталость берет своё. Чет посчитал что 
* Раскрытие IP адреса
* отображать хеш IP адреса

Разные темы. Бывает, давайте в одной обсуждать

**Comment by mj4444ru** [comment]
бляяяяяяяя.... ну в первом же сообщении написано что надо отображать хеш вместо ип....

я против раскрытия настоящего ИП при любых обстоятельствах, даже по судебному решению... и не по тому что я жадный, вредный или у меня велосипеда нет, а по тому что чисто теоретически суд не может обратится к администрации... ну и всё такое...

**Comment by tebaly** [comment]
Нет ни малейшего желания над кем-то издеваться. И никогда не было и не будет, уверяю. Я оч спокойный и добрый человек)

**Comment by mj4444ru** [comment]
tebaly, вы смешная личность...

**Comment by tebaly** [comment]
> я против раскрытия настоящего ИП при любых обстоятельствах, даже по судебному решению... и не по тому что я жадный, вредный или у меня велосипеда нет, а по тому что чисто теоретически суд не может обратится к администрации... ну и всё такое...

Вот поэтому и _показалось_, что темы правильнее было разделить. Всё потому, что мы никого выгораживать не планировали изначально. С самой первой публикации _Пользовательского соглашения_, там прописано:

> 5.6. Администрация вправе, по первому требованию соответствующего уполномоченного правоохранительного и иного уполномоченного государственного органа, но в соответствии с действующим законодательством, передавать такому государственному органу имеющуюся информацию о Пользователе.

При этом всём
*  IP адрес, время обращения - не является запрещенной к публикации информацией

**Comment by tebaly** [comment]
> tebaly, вы смешная личность...

#108

**Comment by tebaly** [comment]
Есть две различные сущности, которые часто путают
* Анонимность
* Безнаказанность

Можно оставаться безнаказанным, благодаря анонимности. Но наш сервис не предназначен для осуществления противозаконных действий. 

> Сайт позволяет сохранять 100% анонимность перед собеседником. Но, в плане совершения противозаконных действий, злоупотребления возможностями сайта и нарушения законов в принципе, анонимности не предусмотрено.

**Comment by tebaly** [comment]
С вашего позволения #109
А в этой ветке продолжим обсуждение первой высказанной идеи
> А давайте в админке будем отображать последний IP адрес человека?

**Comment by mj4444ru** [comment]
Это конечно не было идеей, но всё же повторюсь:

1. В связи с тем, что чисто теоретически ни суд, ни следователи не знают контакты администраторов, они не могут обратится к ним.

2. В связи с тем что вероятность запроса данных может быть связана с компроментированием, личной местью или другим незаконным поводом достаточно высока (и опять же пункт 1), лично я не вижу необходимости делать функционал разглашения ип адреса.

3. Если возникнет ситуация когда действительно адрес будет нужен, можно будет обратится непосредственно к разработчикам.

Я считаю что если суд или другие компетентные органы сделают запрос, то адрес может быть передан только при личной встрече администратора резидента и запрашивающей адрес стороны при наличии соответствующих документов.

В противном случае наши действия могут быть приравнены к соучастию в случае если этими данными воспользуются в незаконных целях.

**Comment by tebaly** [comment]
Поэтому и думаем..

**Comment by inquisitor6789** [comment]
может поясните мне, нафига вам нужен, даже не ИП, а его хэш? Вы способны запомнить строку "jkllkjsdfwwpktkm mspwe[plq-=348lslkmc"? Что это даст кроме расчесывания своего эго? Если хотите мониторить клонов, то доверьте это автоматике. Пусть скрипт шерстит базу и создает список тех, кто зашел с одного ИП.
Кроме того, будет много... Нет, нет так. БУДЕТ ОХЕРЕННО МНОГО ложных срабатываний. Пример из реальной жизни. Абонентов билайн в России порядка 50 млн. Все они выходят в инет через 10 (ДЕСЯТЬ, КАРЛ) шлюзов. Соотв, в статистике сайта будут отображаться эти 10 адресов (насколько я знаю, то в IP-пакете как source address отображается адрес последнего узла). Даже если предположить, что через билайн с телефона заходят всего 1000 человек это будет минимум 100 ложных срабатываний (кол-во пользователей поделить на кол-во шлюзов).
Так же не забываем про прокси.
Если этот пример не устраивает, то вот вам другой. Для большинства локальных сетей используется один и тот же пул адресов 

- 10.0.0.0 — 10.255.255.255 (маска подсети для бесклассовой (CIDR) адресации: 255.0.0.0 или /8)
- 172.16.0.0 — 172.31.255.255 (маска подсети для бесклассовой (CIDR) адресации: 255.240.0.0 или /12)
- 192.168.0.0 — 192.168.255.255 (маска подсети для бесклассовой (CIDR) адресации: 255.255.0.0 или /16
https://ru.wikipedia.org/wiki/%D0%A7%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D0%B9_IP-%D0%B0%D0%B4%D1%80%D0%B5%D1%81

Как вы думаете сильно ли вам это поможет при определении клонов?

Думаю, что лучше будет копать в сторону получения информации по клиентскому оборудованию

mj4444ru, твой алгоритм работает только для IPv4, а как же IPv6?

**Comment by mj4444ru** [comment]
мой алгоритм работает для IPv4, IPv6, IPv10 и так далее... технически может быть 2 IP и более... у опсосов не 10 ип, и даже не 1000, а значительно больше...
я знаю что предлагаю...

**Comment by inquisitor6789** [comment]
> $i1_start = 1; $i1_stop = 1;
$i2_start = 1; $i2_stop = 254;
$i3_start = 1; $i3_stop = 254;
$i4_start = 1; $i4_stop = 254;
...................
$ip = "$i1.$i2.$i3.$i4";

и после этого вы мне будете говорить про IPv6?

> технически может быть 2 IP и более...

да, выдаваться может 2 и более на устройство, но использоваться только 1 в одном пакете.

**Comment by mj4444ru** [comment]
Это фрагмент кода для проверки!!! алгоритма скрытия простого IPv4 адреса.

Сергей, вы хорошо знакомы с протоколом TCP ?

**Comment by mj4444ru** [comment]
#109 

в связи с некоторыми комментариями хочу пояснить.

1) этот метод для краткосрочной идентификации клонов, то есть в рамках одной интернет сессии
сессии могут быть и достаточно длинными в случае выходя через вайфай (свыше месяца)
или достаточно короткими в случае плохой сотовой связи (до 5 минут)

2) идентификатор будет представлять из себя число длинной до 10 цифр

3) он строится не тупо на базе IP адреса (это уже технический момент)

4) выводите дополнительно crc32 от sexid, это позволит увидеть картину шире

5) это не против умных, это против большинства

6) это не инструмент для выявления клонов с целью блокировки, это инструмент для помощи в определении клонов.

**Comment by tebaly** [comment]
> в связи с некоторыми комментариями хочу пояснить.

Завели же отдельный тикет.. Я вам там отвечу

**Comment by inquisitor6789** [comment]
> Сергей, вы хорошо знакомы с протоколом TCP ?

смотря что требуется. Основы знаю.

И мне не совсем понятно с какой целью это хотите сделать. Если для "краткосрочной идентификации клонов", то поясните мне темному, что вы с этой информацией будете делать?

**Comment by tebaly** [comment]
Переходите на светлую сторону. Давайте ХЭШ и UID обсуждать в #109 
Здесь сугубо _Реальный IP_

**Comment by inquisitor6789** [comment]
да какая разница в каком виде ИП адрес показывать.
Пока не пойму что с ним собираются делать (кроме поиска клонов глазами с точностью МЕНЕЕ 50%) мне в поддержку этой идее сказать нечего.
Все аргументы contra я перечислил выше.

ЗЫ. мультиводство не запрещено на сайте
ЗЗЫ. методы вычисления клонов уже обсуждались тут https://github.com/tebaly/freedomsex/issues/40

**Comment by tebaly** [comment]
@inquisitor6789 это один из инструментов, вполне логичный.

* имеем список "похожих" анкет
* заглядываем в каждую

Что можем увидеть?
* одинаковые или идентичные принятые жалобы
* похожие еще не принятые жалобы
* похожие замечания
* кричащий лог воздействий

Это позволит применить к нарушителю "Особое наказание" и предотвратить дальнейшие злоупотребления. 
* это не единственный инструмент, а один из

**Comment by tebaly** [comment]
Так как потребностей в "Раскрытии IP адреса" никто так и не высказал, этот тикет закрывается.
Пожалуйста, для обсуждения UID клиента есть своя тема. Благодарю за понимание.

Спасибо за участие в обсуждении.
