### ISSUE TITLE
История статусов

### ISSUE THREAD

**Issue by mj4444ru** [tebaly/freedomsex#106]
Уважаемы разработчики, а добавить изменение статуса в виде например синего комментария не судьба было сделать?
Будет видно кто какие комментарии ставил...

**Comment by tebaly** [comment]
>  ... изменение статуса ... кто какие комментарии ставил ...

У меня сейчас мозг и так плохо соображает. Как вы увязали статус с комментарием, при условии того, что мы недавно разделили эти сущности на две независимые.

**Comment by tebaly** [comment]
Вроде дошло
* автоматическая публикация комментария при изменении статуса в профиле
* вариант комментария `...`

Ну так же понятнее

**Comment by tebaly** [comment]
Давайте обсуждать

* задумывалось выделить "комментарии" как отдельную сущность

Можно
* впихнуть в комментарии "изменение статуса" при каждой смене
* факт выдачи особого наказания со ссылкой на админа - при каждой выдаче

При этом будет нарушен принцип 
* Принцип единственности ответственности (The Single Responsibility Principle)

На это можно в принципе забить, но
* мы решили выделить особые наказания в отдельный раздел
* точно также можно выделить лог статусов

Какую принципиально значимую информацию вам даст лог изменения статуса

**Comment by mj4444ru** [comment]
Комментарий, это комментарий, сообщения это сообщение...
Я же предлагаю при написании комментария добавлять ещё его в виде сообщения специального типа. Это всё для истории, будет давать ясность в дальнейшем... Люди будут лениться писать сообщения, оставляя лишь комментарии которые позже затрутся...

Я мыслю как программист. Зачем городить кучу всякой фигни, когда можно сделать универсальное сообщение.
Можно ввести 3 типа сообщений.

1. обычное.
2. автоматическое сообщение об изменении комментария.
3. автоматическое от имени Юли об изменении анкетных данных.

Особое наказание это по части кредитов доверия и должно остаться там где оно есть сейчас на его логически правильном месте, только с указанием автора особого так сказать...

**Comment by inquisitor6789** [comment]
> Особое наказание это по части кредитов доверия и должно остаться там где оно есть сейчас на его логически правильном месте, только с указанием автора особого так сказать...

https://github.com/tebaly/freedomsex/issues/76

**Comment by mj4444ru** [comment]
http://freedomsex.net/userinfo/profile/12337922/
Вот видите, люди обновляют статус вместо комментария
Мои предложения исключат это всё

**Comment by inquisitor6789** [comment]
> http://freedomsex.net/userinfo/profile/12337922/
Вот видите, люди обновляют статус вместо комментария

а какой смысл мне писать еще и коммент, если все что хотел сказать укладывается в статус. Насколько я понял задумку комментов, то они нужны в случае отслеживания по профилю. Или для обсуждения

**Comment by mj4444ru** [comment]
а какой смысл писать имя, если за тебя это Юля может написать?

**Comment by inquisitor6789** [comment]
фиксация нарушения, не более
раньше были срачи на счет анкет, по которым менялось имя и пол

**Comment by tebaly** [comment]
> Или для обсуждения

Основная задача

**Comment by mj4444ru** [comment]
я посмотрю как и что вы там собрались обсуждать... и будете ли вообще через месяц что то обсуждать...

а я предлагаю реально полезные фичи которые сейчас нужны и есть красивый и простой способ это реализовать...

**Comment by tebaly** [comment]
> фичи которые сейчас нужны и есть красивый и простой способ это реализовать...

Единогласно. Делаем.

**Comment by tebaly** [comment]
Реализовано в качестве теста
http://qbsex.ru/userinfo/profile/12417665

Если честно, х*йня. 
* В 90% случаев имеем дублирующую статус ЕДИНСТВЕННУЮ информационную запись в комментариях
* Так как это дубль, то с той же вероятностью - это мусор в профиле

Переделаем в отдельный лог статусов по ссылке, так как кроме последнего статуса, вся их история нужна крайне редко.

**Comment by tebaly** [comment]
Использование _Статуса_ как комментария теперь будет функциональной ошибкой
* Статус изначально имеет ограничение на количество символов
* Не стандартный статус не отображается полностью ни в списке пользователей, ни в профиле

> люди обновляют статус вместо комментария

Если этого достаточно, то всё норм.

**Comment by tebaly** [comment]
> я посмотрю как и что вы там собрались обсуждать... и будете ли вообще через месяц что то обсуждать...

Зачем столько страсти. Я лично помню как Администраторы, не имея иной возможности лепили "основания" через тире в статусе. Теперь статус можно не трогать, а "основание" добавлять комментарием. Это только начало
http://freedomsex.net/userinfo/profile/12483310/

И мне по приколу :)
http://freedomsex.net/userinfo/profile/10473301/

**Comment by tebaly** [comment]
@mj4444ru вот шедевр :sweat_smile:
http://freedomsex.net/userinfo/profile/12309560/

**Comment by inquisitor6789** [comment]
полет нормальный. Функционал работает и востребован. топик можно закрывать :-)

**Comment by tebaly** [comment]
> История статусов

Ещё не реализовано

**Comment by tebaly** [comment]
Для истории статусов выбран второстепенный приоритет
* не будет отображаться непосредственно в профиле
* для просмотра истории необходимо перейти по ссылке
* ссылка на истории будет в профиле

**Comment by tebaly** [comment]
Реализовано

Пожалуйста, 
* откройте новую тему, по данному инструменту, если есть вопросы
* помогите написать новость по данному обновлению
