### ISSUE TITLE
История анкетных данных

### ISSUE THREAD

**Issue by mj4444ru** [tebaly/freedomsex#107]
Коль уж замутили сообщения, пусть многоуважаемая и всем надоедающая Юля пишет сообщение типа "Пользователь сменил имя с Александр, на Александра"
или типа "Пользователю было 30 лет, а тут внезапно он помолодел до 16"
ну или вообще "Пользователь сменил пол на Женский"

**Comment by mj4444ru** [comment]
зЫ: первые 10-15 минут можно не фиксировать изменения, пусть определится кто он на самом деле...

**Comment by tebaly** [comment]
#3

**Comment by tebaly** [comment]
Там ошибочка по логам вышла, над предложением работаем в данный момент
