### ISSUE TITLE
Автоматическая регистрация (как термин)

### ISSUE THREAD

**Issue by mj4444ru** [tebaly/freedomsex#11]
Некоторых людей напрягает автоматическая регистрация, при том что акцент сделан на то что сайт не требует регистрации.
Стоит поменять термин на "Идентификация", "Идентификационные данные" и т.д., тогда вопросов не будет.

**Comment by tebaly** [comment]
Запутываете. Общение **анонимное**. Тематика не подразумевает никакой _идентификации_ пользователей в принципе. Регистрации нет как таковой. Сайт без регистрации, в скобках - регистрация автоматическая. Но, при ближайшем рассмотрении, пользователь САМ указывает все регистрационные данные или ИСПРАВЛЯЕТ сгенерированные. Поэтому - _регистрация_ есть, и _самая обычная_, просто размазана по времени и по всему сайту ровным слоем. Или я чего-то не понимаю.
