### ISSUE TITLE
А раскажите как вы это сделали? я не смог (((

### ISSUE THREAD

**Issue by mj4444ru** [tebaly/freedomsex#110]
#109

**Comment by mj4444ru** [comment]
`$hash = [];
$c = 0;
$i1_start = 1; $i1_stop = 1;
$i2_start = 1; $i2_stop = 254;
$i3_start = 1; $i3_stop = 254;
$i4_start = 1; $i4_stop = 254;
for ($i1 = $i1_start; $i1 &lt;= $i1_stop; $i1++) {
    for ($i2 = $i2_start; $i2 &lt;= $i2_stop; $i2++) {
        for ($i3 = $i3_start; $i3 &lt;= $i3_stop; $i3++) {
            for ($i4 = $i4_start; $i4 &lt;= $i4_stop; $i4++) {
                $c++;
                $ip = "$i1.$i2.$i3.$i4";
                $h = crc32(substr(md5("$ip jfgniuwejhpawgjpawhgpgn"), 1, 5));
                if (isset($hash[$h])) {
                $hash[$h]++;
                } else {
                    $hash[$h] = 1;
                }
            }
        }
    }
}`

**Comment by tebaly** [comment]
http://linuxforum.ru/markdown
