### ISSUE TITLE
Список комментариев в админке

### ISSUE THREAD

**Issue by mj4444ru** [tebaly/freedomsex#111]
Может сделать список всех всех комментариев в админке в хронологическом порядке с сылками для перехода в профили?

Типа я пишу комментарий "Предлагаю заблокировать пользователя так как........". Другие админы увидят этот комментарий в общем списке и если согласны, делают блокировку и т.д.

**Comment by tebaly** [comment]
Да, запланировано в раздел "Активности" - продумываем оформление

**Comment by mj4444ru** [comment]
А давайте в раздел "Пользователи", правее пунктов "Активные :: Утопленники :: Настойчивые"

**Comment by tebaly** [comment]
Так это и не "Пользователи" совсем. 
* туда можно и статусы впихнуть
* и комментарии
* и наказания
* и блокировки
* и отмены блокировок

Список можно продолжить

**Comment by tebaly** [comment]
Кстати, о слониках
* в каждом профиле можно выделить _такой_ раздел, с активностями по конкретному пользователю

**Comment by tebaly** [comment]
Давайте медленно заменим "Лог воздействий" на "Лог активности"...

**Comment by mj4444ru** [comment]
технически это может быть один лог, а по удобству размещения в интерфейсе в одной куче мне кажется не очень...

но комментарии это всё таки отдельно... лог воздействий отдельно... одно с дпугим смешивать не надо... комментарии должны жить вечно, а лог активности/воздейтсвий имеет смысл за последнюю неделю и не более 300 записей...

**Comment by tebaly** [comment]
Что имеем на данный момент
* лог статусов по профилю 
* комментарии по профилю 

Можно
* общий список статусов 
* общий список комментариев

**Comment by tebaly** [comment]
Нужен ли общий список статусов - думаю пользы мало, хотя..

Закрываем идею с "Активностями", создаем раздел "Комментарии"?

**Comment by tebaly** [comment]
Реализовано
http://freedomsex.net/history/comments/
