### ISSUE TITLE
Откройте секрет что за красная полосочка появилась

### ISSUE THREAD

**Issue by mj4444ru** [tebaly/freedomsex#112]
Откройте секрет что за красная полосочка появилась в профиле
В случае чего она растёт и что будет когда дойдёт до конца?

**Comment by tebaly** [comment]
Интуитивно понятный интерфейс :copyright:
* при отображении за 100% взято значение 40 каптчи
* итого - полная полоска, значит наказывать хватит (40 каптч <)
* много красного - сильно провинился (40 каптч >)
* отсутствие красного - не виновен (относительно) (0 каптч)
* половинка - почти виноват (~20 каптч)

**Comment by tebaly** [comment]
Ничего не будет - просто информация
