### ISSUE TITLE
Бездна и что с ней делать

### ISSUE THREAD

**Issue by mj4444ru** [tebaly/freedomsex#113]
1. Что такое бездна?
это оставленные пользователями жалобы, но не отправленные на голосование?
или это сообщения которые автоматика посчитала подозрительными, но пользователь на них не жаловался?

2. Что делать с сообщениями в бездне?
в каких случаях необходимо отправлять сообщения в арбитраж? (сообщения каких типов "Вирт, Наказано, Блокировано") необходимо отправлять в арбитраж?

**Comment by tebaly** [comment]
Ну вот, сами(Администраторы) просили с ними что-то делать, а теперь не знаете что именно))
#93
#95 
#75

**Comment by tebaly** [comment]
Ничего.. Если только есть что-то, по чему принципиально необходимо вынести решение.
* сбросить в арбитраж

**Comment by tebaly** [comment]
Подготовим информацию для справки - не успеваем всё сразу. Вы(Администраторы) можете накидать черновиков, потом оформим

**Comment by mj4444ru** [comment]
Простите, часть обсуждений пропускаю....

вот пример полезности серого раздела
http://freedomsex.net/userinfo/profile/?id=12250185

**Comment by tebaly** [comment]
Да. Всё верно
