### ISSUE TITLE
Взаимный обмен фотографиями

### ISSUE THREAD

**Issue by mj4444ru** [tebaly/freedomsex#12]
Люди часто не честны, на это много жалоб, много фейков.
Сделайте функцию "Взаимный обмен фото", когда человек отправляет фотку, но отобразится она другому человеку только если он в ответ вышлет своё фото.

конечно нет гарантии что там будет именно фото а не картинка, но в этом случае у человека хотя бы будет возможность пожаловаться.
естественно необходимо продумать защиту от моментального удаления своего фото после обмена.

**Comment by tebaly** [comment]
> нет гарантии что там будет именно фото а не картинка

Именно. Реализация всё только усложнит. Наши рекомендации остаются неизменны:

> Делайте и отправляйте фото, которые не жалко сделать или отправить. Не отправляйте компрометирующих фото

Вот и всё. Не нужно усложнять, давайте сначало идеально реализуем задуманное - простой и быстрый обмен сообщениями и фото, общение и знакомство.
