### ISSUE TITLE
Особое наказание, что есть что

### ISSUE THREAD

**Issue by mj4444ru** [tebaly/freedomsex#136]
Объясните терминологию в особом наказании

Например анкета http://sexoo.ru/userinfo/profile/7463374

25.06 ` 15:11 (10) - [вычет, траст] - trust: 10
25.06 ` 14:58 (10) - [модератор] - вердикт
25.06 ` 14:11 (3) - [модератор] - перевод с уровня 2
25.06 ` 14:04 (3) - [модератор] - перевод с уровня 1
25.06 ` 14:03 (3) - [модератор] - перевод с уровня 0
25.06 ` 14:00 (0) - [жалоба] - сообщение 0|99357602
25.06 ` 14:00 (0) - [жалоба] - сообщение 1|99357852
26.06 ` 11:12 (2) - [жалоба] - сообщение 0|99524249
26.06 ` 05:36 (1) - [сообщение] - факт: preset: town [1]
26.06 ` 05:32 (1) - [сообщение] - факт: preset: age [1]
26.06 ` 05:32 (1) - [сообщение] - факт: preset: virt [1]
26.06 ` 01:01 (1) - [сообщение] - факт: фото начало [1]

и есть ещё много интересных, например в виде циферок (240 если не ошибаюсь)

**Comment by tebaly** [comment]
Лог воздействий

Является техническим блоком. Может быть скрыт или закрыт в будущем. Содержит отладочную информацию для разработчиков.

**Comment by mj4444ru** [comment]
я считаю это полезно для админов, я часто туда смотрю...
