### ISSUE TITLE
Хотелось бы понять, принцип списка контактов "Удалено".

### ISSUE THREAD

**Issue by Fenslau** [tebaly/freedomsex#139]
Это баг или фича?
Всегда считал, что туда попадают те, кого мы блокируем в анкете (типа игнора) и те, кого наказываем методом наказать и удалить.
Недавно зашел туда и обнаружил там огромную кучу народа! Причем среди них были те, с кем я когда-то общался. И сам я их туда не заносил, инфа 146%. Ссылки разблокировать нету. Вот пример: 
http://hdd.tomsk.ru/desk/uinymeiv#
На скрине 4 видно что в списке удаленных у меня некая Ирина, которая даже фотку присылала мне какую-то. Я вспомнил, что мы с ней общались. Но посмотрев скрин 5 мы можем убедиться, что не написано "начало общения: ...", хотя вроде бы эта фишка уже была реализована?
Туда попали почти все, с кем я когда-то переписывался, но потом перестал.
А что будет, если кто-то из них захочет написать? Сообщение не дойдет?
Можно подумать, что туда попадают те, с кем удаляется "переписка за давностью лет", но остальные из них спокойно висят в списке обычных контактов, хотя переписка уже удалена. Получается, что сначала удаляется переписка, а спустя еще какое то время и сам пользователь из обычного списка? И сам факт бывшего общения скрывается?

**Comment by mj4444ru** [comment]
Там те с кем давно не общался, но они не блокированы, писать могут...
