### ISSUE TITLE
Результат поиска с разграничением по дате последнего входа

### ISSUE THREAD

**Issue by mj4444ru** [tebaly/freedomsex#14]
Добавить в результаты поиска дату посещения сайта и/или сделать разграничительные полосы по  группам:
- онлайн
- был менее часа назад
- был сегодня
- был вчера
- был менее недели назад
- был менее месяца назад

**Comment by tebaly** [comment]
Было изначально, убрали. Теперь эта инфа доступна только в самой анкете. Сделано так не из лучших побуждений.
