### ISSUE TITLE
Фото в первом сообщении с услугами и ценами

### ISSUE THREAD

**Issue by mj4444ru** [tebaly/freedomsex#140]
http://freedomsex.net/userinfo/profile/12411605/

Мне кажется тут автоматика может справиться, подумайте...
или блокировать или количество капч увеличивать...

**Comment by tebaly** [comment]
> 5 дней анкете 

Мы вроде не так давно фильтры поставили.

> Мне кажется тут автоматика может справиться

Опишите

**Comment by mj4444ru** [comment]
я не знаю тонкостей и особенностей ваших фильтров и лишь обращаю внимание...

я бы сделал так:

1. при поступлении 5 жалоб на фото, фото автоматически блокируется (желательно по хешу) и скрывается у всех пользователей, при этом хозяин ничего не должен заподозрить и должен думать что он и дальше успешно шлёт фото...
2. если администратор видит такое фото, то он его блокирует  (желательно по хешу) и оно скрывается у всех пользователей, при этом хозяин ничего не должен заподозрить и должен думать что он и дальше успешно шлёт фото...
3. если человек шлёт первым сообщением фото 10 раз подрят, он автоматически блокируется, при это фото так же удаляется, а нарушитель ничего не должен заподозрить...

**Comment by tebaly** [comment]
№1 + №2 - #63 

> если человек шлёт первым сообщением фото 10 раз подрят, он автоматически блокируется, при это фото так же удаляется, а нарушитель ничего не должен заподозрить...

Просто за фото? Нет же такого правила

**Comment by mj4444ru** [comment]
> Просто за фото? Нет же такого правила

Можно запретить начинать общение с фото
В любом случае это очень плохая ситуация когда так знакомяться с помощью рассылки фото... Нормальные люди так не делают...

**Comment by mj4444ru** [comment]
> №1 + №2 - #63

Хеш это лишь дополнительный функционал, к самой идеи отношения не имеет...

**Comment by tebaly** [comment]
> Изначально я про фото... они же одно загруженное фото рассылают обычно...

А его иначе как по контрольной сумме не определить (индексация содержимого фотографий), и для начала нужно #63 закрыть

**Comment by tebaly** [comment]
Идея в принципе повторяется. Я пока закрою
