### ISSUE TITLE
Проблема с капчей

### ISSUE THREAD

**Issue by mj4444ru** [tebaly/freedomsex#141]
http://freedomsex.net/userinfo/profile/?id=12541484
http://freedomsex.net/admin/sethelp/?id=141616&ln=0

У человека явно техническая проблема с капчей, а Юля ему такое отвечает
не удевительно что человек обиделся и ушёл

**Comment by tebaly** [comment]
#142

**Comment by mj4444ru** [comment]
я тут про капчу писал, а не про злого админа...

**Comment by mj4444ru** [comment]
http://freedomsex.net/userinfo/profile/12564319
подозреваю тоже проблема с капчей... пытались вводить но не смогли...
