### ISSUE TITLE
Завёлся злой админ

### ISSUE THREAD

**Issue by mj4444ru** [tebaly/freedomsex#142]
http://freedomsex.net/admin/sethelp/?id=141727&ln=0
http://freedomsex.net/admin/sethelp/?id=141616&ln=0

**Comment by tebaly** [comment]
Вроде этот http://freedomsex.net/argue/profile/12252697

Сделаем отображение Лога ответов. В дальнейшем продолжим работу над Help-ом

**Comment by tebaly** [comment]
Реализовано в тестовом режиме
http://qbsex.ru/history/rehelp/

Кроме как здесь, ссылки на этот инструмент нигде нет, и кроме вас о нем никто не знает

**Comment by inquisitor6789** [comment]
в принципе не плохо, но хотелось бы скрыть предопределенные (автоматические) ответы. Информации в них ноль и они только забивают ленту

**Comment by mj4444ru** [comment]
лучше вопрос в лог писать для полной картины
