### ISSUE TITLE
Пункты в анкете пользователя.

### ISSUE THREAD

**Issue by Fenslau** [tebaly/freedomsex#145]
http://sexoo.ru/admin/sethelp/?id=141794&ln=141769
Пользователь не может найти, где в анкете удалить информацию про длинные вьющиеся волосы :)

**Comment by tebaly** [comment]
Ну не само же оно поставилось.. Как-то сам сделал же (функционал спрятан, но работоспособен). Тот функционал на стадии отключения. Спрашивается, на кой он туда полез

**Comment by tebaly** [comment]
У него доисторическая анкета была. Очистил
