### ISSUE TITLE
Непонятные обращения к Юле

### ISSUE THREAD

**Issue by mj4444ru** [tebaly/freedomsex#148]
http://freedomsex.net/admin/sethelp/?id=141840&ln=0
http://freedomsex.net/admin/sethelp/?id=141842&ln=141844
Вы точно ничего не сломали?

**Comment by mj4444ru** [comment]
#149

**Comment by tebaly** [comment]
Мы можем многое :copyright:

Особенно во время hot-fix - вчера весь сайт положили минут на 15 ...
