### ISSUE TITLE
Новый дизайн анкеты...

### ISSUE THREAD

**Issue by mj4444ru** [tebaly/freedomsex#149]
Чё за вредительство... Я сам не сразу допёр как анкету теперь увидеть...
Верните... Вместо того чтобы сделать то что давно обещали, только хуже сделали...

**Comment by mj4444ru** [comment]
Это уже не смешно
![net_anketi](https://cloud.githubusercontent.com/assets/9354685/16365811/456d9452-3c24-11e6-9bc3-996f7057853d.PNG)

**Comment by tebaly** [comment]
Понятия не имею о чем речь. У меня норм

**Comment by tebaly** [comment]
Почистите кэш - может поможет. Отключите адблок

**Comment by tebaly** [comment]
#148
