### ISSUE TITLE
На странице истории ответов Юли не хватает

### ISSUE THREAD

**Issue by mj4444ru** [tebaly/freedomsex#150]
На странице истории ответов Юли не хватает ссылки на историю переписки...

**Comment by tebaly** [comment]
Ок. Счас

**Comment by tebaly** [comment]
Обнулил историю лога, ссылка на переписку не сохранялась. С этого момента по новой собирает (другая инфа осталась, если понадобится). К новой у вас теперь полный доступ.

Спасибо.
