### ISSUE TITLE
запретить отправлять первое сообщение в виде фото.

### ISSUE THREAD

**Issue by Fenslau** [tebaly/freedomsex#151]
ничего не потеряем (конечно же сделать это незаметно).
В принципе, те, кто отправляют фото первым сообщением - не особо полезны. Это в основном спамеры. Врядли нормальный человек, даже который законченный там нетрадиционник, начнет с этого. Так делают ленивые спамеры, которые рассчитывают на моментальный эффект от своих стручков (ну или тролли).

**Comment by mj4444ru** [comment]
#140

**Comment by Fenslau** [comment]
Принципиально запретить. Даже без хешей, даже без чего-бы то ни было. Первое - фото - игнор сообщения. Ладно, раз идея повторяется - закрывайте.

**Comment by mj4444ru** [comment]
#19

**Comment by tebaly** [comment]
@Fenslau да, обсуждалось. Запрещать отправку фотографий не самый оптимальный путь, мне кажется.
