### ISSUE TITLE
Профиль нарушителя (Предложено 0, принято 161 знакомств)

### ISSUE THREAD

**Issue by mj4444ru** [tebaly/freedomsex#152]
27.06 ` 21:58 (1) - [сообщение] - факт: фото начало [1]
27.06 ` 21:36 (1) - [сообщение] - факт: фото начало [1]
27.06 ` 21:03 (1) - [сообщение] - факт: фото начало [1]
27.06 ` 18:03 (1) - [сообщение] - факт: фото начало [1]
27.06 ` 17:49 (1) - [сообщение] - факт: фото начало [1]
27.06 ` 17:12 (1) - [сообщение] - факт: фото начало [1]
27.06 ` 16:28 (1) - [сообщение] - факт: фото начало [1]
27.06 ` 15:08 (1) - [сообщение] - факт: фото начало [1]

Это как понимать? фото было выслано в ответ вместо текста?
думал фото начало это когда юзер первый пишет, а тут вроде как предложено 0...

**Comment by tebaly** [comment]
Первое `от`. То есть моё вам сообщение первое, а в переписке второе.
