### ISSUE TITLE
32 капчи за жалобу

### ISSUE THREAD

**Issue by mj4444ru** [tebaly/freedomsex#156]
Лог воздействий
28.06 ` 10:15 (32) - [жалоба] - сообщение 4|99894975
28.06 ` 09:23 (6) - [жалоба] - сообщение 0|99888594
27.06 ` 23:08 (4) - [жалоба] - сообщение 0|99831378
27.06 ` 18:38 (4) - [жалоба] - сообщение 0|99786691
27.06 ` 18:11 (2) - [жалоба] - сообщение 0|99782421

Это как это вообще такое возможно?
причём 3 жалобы зелёных/ложных

**Comment by tebaly** [comment]
#136 

> Лог воздействий является техническим блоком. Содержит отладочную информацию для разработчиков.

Благодарю за обращение
