### ISSUE TITLE
сообщения от несовершеннолетних

### ISSUE THREAD

**Issue by inquisitor6789** [tebaly/freedomsex#157]
тут у меня с @9791041 ака @mj4444ru вышел спор на счет сообщения http://freedomsex.net/history/message/99783280/
согласно регламенту, соглашениям и прочим регулирующим документам сайта сообщение не содержит криминала. В отличии от http://freedomsex.net/history/message/99749675/
@9791041 настаивает на блокировке сообщения. Я настаиваю на том чтобы его разрешить.
его аргумент 
>ты пойми, мы не сообщение оцениваем, а даём системе указание как поступать в дальнейшем при таких же сообщениях... 
если мы отметим как блокировать, когда он в след раз такое же напишет, система его автоматом блокирнет...
по этому важно оценивать сообщения без контекста, так как в следующий раз контекст может быть другой и система может ошибится...
тут однозначно можно поместить в блокируемые, при любом контексте это повод для блокировки анкеты...

в связи с этим вопрос - какова будет позиция сообщества? Либо мы все сообщения несовершеннолетних (там где указан возраст) блокируем, либо действуем как сейчас (если сообщение не содержит противоправного содержания, то разрешаем сообщение)

**Comment by mj4444ru** [comment]
дополнение
мы ранее определились что блокируем анкеты менее 16 лет

**Comment by inquisitor6789** [comment]
> мы ранее определились что блокируем анкеты менее 16 лет

я это и не оспариваю. однако, в данном топике речь идет именно о сообщениях. Без привязки к анкете

**Comment by tebaly** [comment]
> ты пойми, мы не сообщение оцениваем, а даём системе указание как поступать в дальнейшем при таких же сообщениях... 

Это грубая ошибка администрирования. И самовольное толкование действия системы сайта, правил сайта, регламента и Соглашений

http://freedomsex.net/мониторинг-решений/ - содержит чёткое определение в последнем абзаце

> При принятии решения по содержанию жалобы, **рассмативается только текст и содержание жалобы**. _Ни содержание профиля нарушителя, ни премененные ранее наказания, ни замечания к анкете не имеют значения при этом_. Равносильно **возраст пользователя**, город или имя на это тоже не влияют, _как и содержание других жалоб, на этого же пользователя_. Содержание жалобы нужно оценивать **в отрыве от контекста**, что необходимо из-за технической особенности работы системы.

**Comment by tebaly** [comment]
Вы **можете блокировать** АНКЕТУ пользователя по пунктам правил:
* Провокации пользователей или Администраторов
* Незаконное содержание

Действия @mj4444ru я могу квалифицировать не иначе как
* 12.3. Провокация _Администраторов_ сообщества незаконным содержанием сообщений и/или фотографий может расцениваться как запрещенное действие, даже при фактической законности такого содержания.

Это уже третий намек для него, и негласно, _последнее_ китайское предупреждение. При всём моём уважении, и все благодарности за оказанную помощь и содействие в администрировании ресурса. Я заблокирую @mj4444ru и лишу всех его полномочий не взирая ни на что, при малейшем прикосновении его к этой теме в ближайшую половину года.

**Comment by tebaly** [comment]
В правилах данная тема на все 146% освещена

**Comment by tebaly** [comment]
@mj4444ru - вам крайне не рекомендовано участие в рассмотрении жалоб, и принятия решений в отношении Нарушений, относящихся к данной теме.

**Comment by tebaly** [comment]
До **1 сентября** вводится режим тишины на обсуждение данной темы. Всем администраторам:
* рекомендовано игнорирование любых обращений за комментариями
* вы можете расценивать подобные обращения как провокацию незаконным содержанием
* вы можете предоставить ссылки на правила и соглашения в ответ
* вы можете цитировать пункты правил или Соглашений

**Comment by mj4444ru** [comment]
@tebaly, вы опять что то попутали? пока не извинитесь, я больше ничего не делаю...

**Comment by Fenslau** [comment]
Я выскажусь, не претендуя на авторитетность мнения:
По видимому сообщения от одного и того же человека, хотя нам это не особо важно. 
По факту есть два сообщения. В обеих содержится текст, по которому мы можем судить, что пользователь хочет, чтобы собеседник считал, что ему 15 лет, 11 см и он видел маму голой. Это или его фантазии (воспоминания или мечты) или же преднамеренный троллинг и провоцирование. Определить это по контексту (или без него) невозможно. Если это фантазии, то, мне кажется, можно разрешить. Если же никаких искренних фантазий нет, а имеет место троллинг, с целью посмотреть на реакцию или что то такое - то блокировать анкету, но не сообщение. Но мы не определим. 
Я честно говоря, не совсем понял реакцию tebaly. Ведь в действиях mj4444 нет намерений по подрыву принципов действия системы, если я правильно понял, он хочет разобраться. Так давайте разберемся, в споре рождается истина. 
Только без обид и предвзятостей. 
Если мы контекст не принимаем к виду, то нам придется сообщение разрешить, а саму анкету возможно блокировать (особенно, если мы понимаем, что это уже не первая такая анкета). Саму возможность блокировки по таким же сообщениям нужно видимо дорабатывать (с учетом нововведений в виде поиска клонов и т.п.) и потом уже внедрять...

**Comment by mj4444ru** [comment]
идея была использовать существующую систему для автоматической блокировки клонов на основе повторяющихся фирменных сообщений...
я тоже понимаю что в самом сообщении как бы нарушения нет, но предложил блокировать так как: есть предположение что если этот человек повторно отправит это сообщение, анкета автоматически будет блокирована на основе сообщения из чёрного списка... и это я хотел уточнить, так как ну уверен в том что это действительно так...
я не собирался кого то убеждать что в сообщении есть нарушение...

**Comment by Fenslau** [comment]
Если я правильно понял, те, кто против блокировки сообщения защищают ту точку зрения, что само сообщение недостаточно уникально для блокировки. То есть теоретически я завтра могу написать, что мол когда мне было 15 лет, я любил подсмотреть за мамой и в данном контексте это блокировать нельзя. А система может. На основании каких то нам неведомых алгоритмов. 
По этой же причине надо бы вытащить из блокированных сообщений еще кучу контекстных сообщений. А то и вовсе .. подумать...
Фото мы боимся блокировать, а вот сообщения - давно в базе и тыщи их. Там чего только нет. 
http://sexoo.ru/history/message/97822774/
http://sexoo.ru/history/message/97744144/
Это я так, недалеко сходил. Получается что если меня спросит кто-то, куда я там чо ходил платить, почему не отвечал и я отвечу "деньги на телефон (скидывал)", то меня блокируют.

**Comment by Fenslau** [comment]
Короче разработчики не сообщают алгоритм, но он похоже какой-то околоэвристический. В принципе, правильно делают, ведь здесь может оказаться диверсант. Нам остается только строить догадки и скидывать их сюда. Единственно, я допустим, не могу определить уникальность сообщения для блокировки. (самого сообщения). Ясно что такие сообщения как "350" мы не блокируем. А "120 за минуту" ? или речь идет об оборотах или о наборе скорости? ) 
Не зная хотя бы примерно принципа действия, мы не сможем принимать решения. Я вообще отказываюсь от блокировки сообщений в дальнейшем. Никто не напишет никогда: "Я предлагаю тебе 3000 рублей за час секса со мной в реале". Давайте или не доводить до абсурда, или думать, как регламент изменить. Явные предложения, неявные, кто это определит и где грань?

**Comment by mj4444ru** [comment]
Я предполагаю что алгоритм прост: берём сообщение, меняем все символы кроме букв и цифр на пробелы, потом убираем повторяющиеся пробелы и фиксируем что получилось

При поступлении новых сообщений так же обрабатываем, ищем идентичные...

если искать по вхождениям шаблонов чёрного списка, то сообщения типа "у меня телефон на 23000 рублей" или "деньги на телефоне закончились" привели ба к блокировке...

а вот это уже действительно бред http://sexoo.ru/history/message/97744144/
и все кто это видел и не убрали из блокировки, считаю вредителями системы...

**Comment by tebaly** [comment]
Друзья, товарищи, коллеги, Администраторы. Пожалуйста. 

> При принятии решения по содержанию жалобы, рассмативается только текст и содержание жалобы. Ни содержание профиля нарушителя, ни премененные ранее наказания, ни замечания к анкете не имеют значения при этом. Равносильно возраст пользователя, город или имя на это тоже не влияют, как и содержание других жалоб, на этого же пользователя. Содержание жалобы нужно оценивать в отрыве от контекста, что необходимо из-за технической особенности работы системы.

Попробуем тоже самое, в структуре списка. Его легко построить самостоятельно, просто расставляя перенос вместо запятых и немного отформатировать
---

При принятии решения по содержанию жалобы, рассмативается 
* **только текст** 
* содержание жалобы

Полностью ИГНОРИРУЕТСЯ
* содержание профиля нарушителя, 
* премененные ранее наказания, 
* замечания к анкете

Игнорируется ПОЛНОСТЬЮ
* **возраст пользователя**, 
* город
* имя 

Не рассматривается вообще
* содержание других жалоб, на этого же пользователя.

Комментарии 
* содержание жалобы нужно оценивать в отрыве от контекста
* это необходимо из-за технической особенности работы системы

**Comment by tebaly** [comment]
> Если это фантазии, то, мне кажется, можно разрешить. Если же никаких искренних фантазий нет, а имеет место троллинг, с целью посмотреть на реакцию или что то такое - то блокировать анкету, но не сообщение.

> В отличии от ... настаивает на блокировке сообщения. Я настаиваю на том чтобы его разрешить.

# Золотые слова

На этом мне кажется стоит согласиться, что все всё правильно поняли.
* анкету блокировать МОЖНО
* сообщения НЕТ

**Comment by tebaly** [comment]
@Fenslau 

> в данном контексте это блокировать нельзя. А система может.

Да в том то и дело, что нет. Если только не начать блокировку содержимого жалоб по методике, "внедряемой" @mj4444ru - вот тогда да, и это всё выльется в вот это, изучите инцидент 

#84 - это не единичный случай

**Comment by mj4444ru** [comment]
@tebaly вы запарили со своим контекстом... я написал **по этому важно оценивать сообщения без контекста** в самом начали и за это же всегда боролся... вы вообще с кому пытаетесь про контекст это всё вбить? мне кажется все присутствующие это прекрасно понимают...

#84 моя методика не допускает подобные случаи...

Вы запарили меня обвинять в непонятно чём...

**Comment by inquisitor6789** [comment]
> я написал по этому важно оценивать сообщения без контекста

блин, это ты запарил. Вот как раз если без контекста, то сообщение надо разрешить, т.к. это сообщение ничто не нарушает (ни ук, ни регламент, ни еще что-то). Ты же, возможно с благими намерениями, хочешь его блокировать. Следуя твоей логике надо блокировать и сообщения "мне 14" (к примеру).
И если допустить, что СБ использует эвристику при анализе жалоб, то под бан попадет множество анкет не содержащих никакого криминала. Например, если написать что-то вроде "когда мне было 14, я подрачивал каждый день" (тут нет нарушения, но по ключевым словам сообщение может быть заблокировано, а следовательно и анкета)

**Comment by tebaly** [comment]
![](https://i.imgur.com/1JVBqD5h.jpg)

**Comment by Fenslau** [comment]
Сообщение про "деньги на телефон" предлагаю вытащить из блокировки. Пусть это сделает любой, кто уверен, что там блокировать не за что. Я с некоторых пор отношусь к арбитражам сомнительно. Нет желания туда-сюда сообщение одно и то же пинать.

**Comment by mj4444ru** [comment]
> Следуя твоей логике надо блокировать и сообщения "мне 14" (к примеру).

По моей логике за "мне 14" нельзя блокировать анкету... Необходимы дополнительные доказательства, а это уже другой случай...

Да, если буквально понимать, под мой случай можно подгребсти "мне 14 лет"...
И тут есть два варианта:
я уверен что система фильтрации не извращается и не ищет вхождения всех запрещённых фраз, так что похожие фразы (с другим порядком или набором слов) не будут заблокированы...
а если это не так, нас должны предупредить о том что не надо блокировать фразы которые можно дополнить, после чего они перестанут быть опасными...

но разработчики не могут определить чёткие правила и действуют двойными стандартами...

и для них больная тема не блокировка лишних сообщений, а тема педофилии, которая явно неудачно была выбрана примером...

**Comment by mj4444ru** [comment]
> Сообщение про "деньги на телефон"

Эт капля в море, не заморачивайтесь...

**Comment by mj4444ru** [comment]
#167 

1. При принятии решения о блокировке жалобы, вы блокируете содержание сообщения, в не зависимости от того, кто и когда отправит подобное сообщение в будущем.
2. Ошибки в применение с этой целью контурной защиты могут навредить реальным пользователям.
3. Маркировка позволяет системе автоматически принимать решения в будущем, чтобы облегчить работу модераторам и администраторам.
4. Система автоматически реагирует на содержание промаркированной жалобы вне зависимости от того, кем в будущем будет отправлено такое сообщение.
5. Автоматика учитывает только содержание жалобы, поэтому и выставлять маркер "наказано", "блокировано" и тд. нужно только лишь по содержанию жалобы.

> ты пойми, мы не сообщение оцениваем, а даём системе указание как поступать в дальнейшем при таких же сообщениях... 

Указание на пункт 3.

> если мы отметим как блокировать, когда он в след раз такое же напишет, система его автоматом блокирнет...

Указание на пункт 4.

> по этому важно оценивать сообщения без контекста, так как в следующий раз контекст может быть другой и система может ошибится...

Указание на пункт 1, 2, 5.

> тут однозначно можно поместить в блокируемые, при любом контексте это повод для блокировки анкеты...

Указание на то что текст сообщения не противоречит пунктам 1, 2, 5.

Я не знаю какой бред вы ещё можете придумать в своё оправдание... Хотя вы наверно промолчите...

**Comment by tebaly** [comment]
Именно, и вас просили не касаться больше темы, касающейся

> тут однозначно можно поместить в блокируемые

Вы всячески игнорируете не только слова, но и публичные предупреждения.

Это вторая причина вашей блокировки как Администратора.

**Comment by mj4444ru** [comment]
я никоим образом не затрагиваю тему несовершеннолетних... я обсуждаю принципы действия администраторов без учёта темы... я много раз это повторял...

**Comment by tebaly** [comment]
https://github.com/tebaly/freedomsex/blob/deal/doc/deal/812-Обсуждение-действий-администраторов.md
