### ISSUE TITLE
Вопрос по логу воздействий

### ISSUE THREAD

**Issue by Fenslau** [tebaly/freedomsex#160]
Был прецедент принятия решения по логу воздействий. Что говорить, мы на него опираемся. 
Но не все понимают, что означают некоторые строчки в нем. 
Я поддерживаю идею его оставить.
В связи с этим вопрос:
Если такое идет подряд:
28.06 ` 20:17 (1) - [сообщение] - факт: preset: age [1]
28.06 ` 20:03 (1) - [сообщение] - факт: preset: age [1]
28.06 ` 20:02 (1) - [сообщение] - факт: preset: age [1]
28.06 ` 20:02 (1) - [сообщение] - факт: preset: age [1]
28.06 ` 20:01 (1) - [сообщение] - факт: preset: age [1]

Это общение с одним и тем же пользователем, или каждый раз с новым, или возможно что и то и другое?

28.06 ` 15:45 (1) - [сообщение] - факт: 140 [1]

что это? что такое 140?

28.06 ` 17:39 (1) - [сообщение] - факт: спам [3]
28.06 ` 17:39 (1) - [сообщение] - факт: спам [2]

Это означает, что было отправлено одно и то же сообщение? 
А я видел, что пользователь заработал 60 капч за целую серию таких. Как? Разве не предполагается, что он вводит капчу каждый раз, а не пока накопит их 60? Других логов воздействия к тому пользователю не было, только эти спамы.

**Comment by tebaly** [comment]
Это технический лог, только для разработчиков. Мы не можем дать вам расшифровку этих пунктов. Спам, это спам - он запрещен почти везде.

Спасибо за обращение.
