### ISSUE TITLE
А что это в отправленных имя 2зелёных и 1 оранж.

### ISSUE THREAD

**Issue by mj4444ru** [tebaly/freedomsex#162]
http://freedomsex.net/admin/sethelp/?id=142337&ln=142338

сами отвечайте если нам рассказать этого не можете...

**Comment by tebaly** [comment]
Чего не могу? Там всё расписано(!)
* зеленое - новое знакомство без ответа
* оранж - новое сообщение

**Comment by Fenslau** [comment]
Э? Вы про точки слева от имени в списке контактов? Оранж - чот не бьется. У меня сейчас горит оранж точка напротив имени девушки, которой я даже два раза ответил на ее сообщение, а оно все горит и горит. Или я чот недопонял?

**Comment by mj4444ru** [comment]
@Fenslau нас наебали...

**Comment by Fenslau** [comment]
Сначала по диалогу с Юлей я подумал, что юзер спрашивает про оранжевые и зеленые имена в диалоге с девушкой. типа Сначала оранжевое, девушка прочитала - зеленое становится. Потом я вспомнил про эти точки в списке контактов. Если честно, я сам со всеми своими iq не могу разобраться что там и как маркируется. Либо я туплю, либо маркируется неоднозначно.
А юзер мож вообще и о том и об этом одновременно спрашивал )

**Comment by mj4444ru** [comment]
Жёлтые - юзер онлайн...
Зелёные - анкете меньше суток...

**Comment by Fenslau** [comment]
Хер на палке. 
Желтые - не факт вообще что юзер онлайн. Или обновляется долго или мы вообще о разных кружках говорим. 
Зеленых я вообще не встречал.

**Comment by mj4444ru** [comment]
блин, ты прав на счёт жёлтых...

**Comment by Fenslau** [comment]
Седня я уже устал тестить. Если будет новый ответ от разработчиков - потестю. А так гадать не перегадать.

**Comment by tebaly** [comment]
> или мы вообще о разных кружках говорим

На чёткий вопрос можно дать конкретный ответ. Как отвечать, если суть вопроса у всех разная?

**Comment by Fenslau** [comment]
В списке контактов слева от имени пользователя иногда горит кружок. У меня только оранжевые, но вот некоторые говорят, что еще и зеленые бывают. Собственно говоря, что этот кружок означает? Новое сообщение... Но у меня уже давно горит этот оранжевый кружок, хотя я все сообщения от того пользователя уже прочитал.

**Comment by tebaly** [comment]
> В списке контактов слева от имени пользователя иногда горит кружок. У меня только оранжевые

Онлайн (актуальность 15 минут)

**Comment by tebaly** [comment]
> PS: интуитивно понятный интерфейс...

Мы _намеренно_ выделили в интерфейсе его часть, описания которой нигде нет. Эти элементы не сопровождаются ни подсказками, ни информационными сообщениями - ничем.

В эту часть интерфейса входят именно
* точки в результатах поиска
* маркеры в списке контактов
