### ISSUE TITLE
Я ж не просто так встречаюсь

### ISSUE THREAD

**Issue by mj4444ru** [tebaly/freedomsex#164]
http://freedomsex.net/history/message/99776088/

Наверно все кроме меня считают что это нормально и не приводит вот к этому #84?

**Comment by inquisitor6789** [comment]
аргументы против будут?

**Comment by tebaly** [comment]
У меня нет :)

Вообще, вероятность развития сценария по #84 есть, нужно просто её оценить. 
* если меньше 10% - то нормально, мне кажется

@mj4444ru  тут следующая цепочка
`встреча не за просто так ~ оплата встречи ~ проституция запрещена` - погрешность менее 5%

**Comment by mj4444ru** [comment]
Вы процент по какой формуле считать собрались?

"Я ж не просто так встречаюсь, я встречаюсь для секса"

а на счёт цепочек, это уже у каждого своя фантазия...

**Comment by Fenslau** [comment]
Хорошо, а фраза "Я же просто так не встречаюсь" не попадет под раздачу из за этой блокировки?

**Comment by mj4444ru** [comment]
Врятли... Пусть разработчики скажут...

**Comment by Fenslau** [comment]
Я же не просто так встречаюсь, мне нужно сначала пообщаться.
Я же не просто так встречаюсь, мне нужно хотя бы фото увидеть
Я же не просто так встречаюсь, у меня муж дома и нужно время выбрать подходящее
Я же не просто так встречаюсь, у меня дети и места нет
Я же не просто так встречаюсь, я на этом сайте недавно и еще пока боюсь
...
Всё что после запятой, может быть отправлено вторым сообщением, да только после авто блокировки начального, его уже никто не прочтет...

**Comment by inquisitor6789** [comment]
@Fenslau вам не кажется, что приведенные примеры несколько не по русски звучат?

**Comment by Fenslau** [comment]
Да по сравнению с тем, что порой пишут пользователи,  я просто лев толстой в этом примере. Логическое ударение на слове просто. А не на простотак

**Comment by tebaly** [comment]
Как было заложено изначально, и как есть
* в раздел _блокировано_ помещаются только явные и недвусмысленные по содержанию жалобы
* иные формулировки порождают споры и конфликты, как в данный момент

По этому принципу, данную жалобу стоит отметить "наказано", но не _блокировано_. Но:
* данная фраза с большой вероятностью трактуется именно как `~ оплата встречи`

Как можно
* оценить вероятность _случайной_ блокировки невиновного Пользователя
* оценить вероятность _успеха_ данного содержания в контексте мошенничества/индивидуалки

Итого, поместить в _блокировано_ можно
* если польза от блокирования Нарушителей кратно превышает вред от ложного срабатывания
* если вероятность ложного срабатывания крайне низка, или стремится к нулю

---

В будущем, планируется ввести полуавтоматическую обработку такого контента. С введением пограничного маркера "двусмысленное содержание"
* разрешено-вирт
* разрешено-наказать
* наказать-блокировать
* наказать-вирт
* вирт-блокировать

и т.д.

**Comment by Fenslau** [comment]
То есть, если я правильно понял, эту фразу оценили как однозначное требование оплаты. Хотя в арбитраже она была несколько искажена: "я не за просто так встречаюсь". Давайте конструктивно. У меня нет никакого желания кого-то в чем-то уличать. Я скорее за последовательность. Из этих слов можно построить несколько фраз, разных по смыслу:
+безобидная "Я же просто так не встречаюсь" без контекста это просто сообщение.
+нейтральная "Я ж не просто так встречаюсь" - без контекста это просто сообщение.
+явное требование оплаты "я не за просто так встречаюсь".
Повторюсь: никого не хочу ни в чем "обвинять", но какой смысл домысливать контекст (и изменять порядок слов на "более криминальный"?
А кстати, что с анкетой произошло этой девушки? http://sexoo.ru/userinfo/profile/99776088
Там теперь ничего не видно и вообще всё пропало.

**Comment by inquisitor6789** [comment]
> http://sexoo.ru/userinfo/profile/99776088

айдишником не ошибся? таких анкет еще не существует :-)

**Comment by Fenslau** [comment]
Упс. Точно, не то скопипастил. http://freedomsex.net/userinfo/profile/12562877
Блин, ну конечно возможно, что предлагала оплату, но Даже по контексту это неявно. Нажаловался на нее какой-то стручок. Скинул всё что можно, но только не конкретную просьбу оплаты. Почему? За какую бумагу? Все сообщения вне контекста вообще разрешенные. 
Паранойю если включить, можно до столба доебаться... Ну да ладно, я в общем то подытожу: 
+Лично я сомневаюсь, что речь шла о платных услугах.
+Лично я сомневаюсь, что даже если это так, то стоило эту фразу помещать в блокировано.

**Comment by tebaly** [comment]
>  она была несколько искажена: "я не за просто так встречаюсь"

Так это же всё меняет - два дня сторов _ниачём_... серьёзну, тут без иронии

`не за просто так встречаюсь === за деньги`
