### ISSUE TITLE
Опять непонятки

### ISSUE THREAD

**Issue by mj4444ru** [tebaly/freedomsex#167]
Ну я уже не знаю как это назвать товарищи

http://freedomsex.net/userinfo/profile/?id=11586954

давайте всех перебаним? и споров не будет...

**Comment by mj4444ru** [comment]
![image](https://cloud.githubusercontent.com/assets/9354685/16464646/949e7b72-3e54-11e6-8343-d3af6f7050e0.png)

**Comment by Fenslau** [comment]
Дмитрий, 28 Москва (Парень онлайн)
Предложено 861, принято 0 знакомств 
Жалоб сегодня 1, всего 9, долг 0 капчи
Так, а кто блокировал?

**Comment by mj4444ru** [comment]
![image](https://cloud.githubusercontent.com/assets/9354685/16464756/2572bbf4-3e55-11e6-990d-b21e1a09033d.png)

**Comment by mj4444ru** [comment]
Автоматика... Я специально данные его стёр со скриншота, а ты... (конфидициальность и бла бла бла)...

**Comment by mj4444ru** [comment]
Некий администратор внёс фразу в раздел "блокировать"... Этот человечек видимо всем рассылал одно и тоже и кто то ещё раз пожаловался на эту фразу и автоматика его блокировала...

**Comment by Fenslau** [comment]
здесь кроме нас и Сергея и еще кое-кого всеравно никого нет. 
Какая нахер автоматика? 7680905 Эта? :)

**Comment by mj4444ru** [comment]
Нет, это обычная жалоба...
Автоматика не оставляет следов при блокировки и не объясняет причину... политика разработчиков...

**Comment by Fenslau** [comment]
Погоди. И как давно он автоматикой заблокирован? Как тогда недавняя жалоба на него прошла?

**Comment by mj4444ru** [comment]
29.06 (20:37) --- на него поступила жалоба
29.06 (21:04) - блокировать @7680905 ---- сообщение помещено в блокированные

где то между 21:04 и текущем временем поступила повторна такая же жалоба...
автоматика его и заблокировала...
всё же просто...

**Comment by Fenslau** [comment]
Скажем так, некий вердиктчик.

**Comment by mj4444ru** [comment]
Ты лучше убери эту фразу из блокировано, пока оно пол сайта не переблокировало...

**Comment by Fenslau** [comment]
Я вытащил, но похоже это уже ничего не изменит.. В отношении той анкеты..

**Comment by mj4444ru** [comment]
Ну в отношении той да...

Кстати где такие красивые ID покупал? я тоже такой хочу ))))
11233211

**Comment by Fenslau** [comment]
Как говорят некоторые - "просто спрухало" )
Везение там, где не надо короче )

**Comment by tebaly** [comment]
http://freedomsex.net/блог/мониторинг-решений/ - цитаты:

* При принятии решения о блокировке жалобы, вы блокируете содержание сообщения, в не зависимости от того, кто и когда отправит подобное сообщение в будущем.
* Ошибки в применение с этой целью контурной защиты могут навредить реальным пользователям.
* Маркировка позволяет системе автоматически принимать решения в будущем, чтобы облегчить работу модераторам и администраторам.
* Система автоматически реагирует на содержание промаркированной жалобы вне зависимости от того, кем в будущем будет отправлено такое сообщение.
* Автоматика учитывает только содержание жалобы, поэтому и выставлять маркер "наказано", "блокировано" и тд. нужно только лишь по содержанию жалобы.

@mj4444ru  - можно я публично откажусь отвечать на ваши наезды? Как бы оскорбительно для вас это не звучало - ваши действия, общение и поведение имеют ярко провокационный характер. Благодарю за помощь в развитии и поддержке проекта.

![](http://yasnoponyatno.com/wp-content/uploads/2015/04/bd85exvnrh7y4k362lfmia1tqj0puosgcz9w.jpg)

**Comment by mj4444ru** [comment]
@tebaly Я в своих действиях руководствуюсь именно этими цитатами...
И я говорю всё то же самое, только другими словами...

В этой теме я на вас @tebaly не наезжал... Опять вы не в тему меня обвиняете...

Значит у вас там кто то банит всех подряд, а виноват опять я... Видимо именно в моих действиях в данной теме вы нашли провакационный характер... Вы случаем не с украины?

**Comment by tebaly** [comment]
* Некий администратор внёс фразу в раздел "блокировать"... 
* на эту фразу и автоматика его блокировала...
* и любого кто захочет сегодня потрахаться ждёт такая же участь...

То есть, Вы, полностью понимая принцип работы системы сайта, зная все правила администрирования, по крайней мере касающихся этой ситуации, а именно
* если администратор видит жалобу, ошибочно занесенную в раздел - блокировано
* он понимает, что если не изменить решения по жалобе - невиновные пользователи могут пострадать
* он сбрасывает решение в арбитраж
* выясняет причину ошибки модератора, имея доступ к статистике
* обнаруживает злонамеренные действия модератора в администрировании
* сбрасывает рейтинг модератору, для предупреждения деструктивных последствий
* либо вводит рейтинг в минус, блокируя деятельность зловреда

---

- Вы обнаружили несоответствие в 21:49
- Вы не предприняли никаких действий
- Привели скриншот и данные подтверждающие это 21:56
- Вы проявляете полное бездействие
- Вы рекомендуете другому администратору что либо предпринять в 22:13
- Я сбрасываю рейтинг модератору 7680905 в 00:30

Это первая причина по которой я заблокирую вас как Администратора.

**Comment by mj4444ru** [comment]
1) Вы мне сами запретили принимать решения...

2) Я давно сказал что не буду принимать решения по жалобам пока вы не извинитесь...

3) От меня была в любом случае польза. А вот был ли от меня вред?

4) Я принял все возможные от меня действия, сообщил тут и привлёк внимание к нарушителю...

Больше мне нечего сказать...

В связи с тем что мой рейтинг теперь не позволяет каким любо образом участвовать в поддержании порядка и участвовать в разработке проекта, я вынужден покинуть обсуждения...

**Comment by tebaly** [comment]
> 1) Вы мне сами запретили принимать решения...

И это третья причина по которой мне пришлось прибегнуть к таким действиям.
