### ISSUE TITLE
строка с информацией о том что переписка загружается

### ISSUE THREAD

**Issue by mj4444ru** [tebaly/freedomsex#17]
Она очень маленькая, люди её не видят. Необходимо сделать большими (огромными) красными буквами "История переписки загружается".

**Comment by tebaly** [comment]
Аа. это да. Но так не реализовывает никто. У всех обычно это нейтральная надпись. Проблема появляется когда сервер тупит. В данный момент на загрузку требуется меньше секунды, чаще всего. 

Красными буквами это перебор, большими тоже. Использовать image loader - тут тоже много споров, и сейчас в тренде его не использовать. Причина замечания понятна. Надпись есть, надпись имеет прямое значение. Если ее кто-то не видит..
