### ISSUE TITLE
Предлагаю вытащить из блокированного следующие сообщения:

### ISSUE THREAD

**Issue by Fenslau** [tebaly/freedomsex#170]
2 т.р.
от 500
да! 2500р
1000₽
Внимание Госпожи дорого!
не знаю как деньги прилипают ли,но музыка божественная https://www.youtube.com/watch?v=1e_em9Jw8po (хотя это наверно больше ради принципа, больше так все равно никто не напишет)
после оплаты)
ну и т.д., не знаю, есть ли смысл перечислять больше. 
В рамках борьбы с контекстом.

**Comment by tebaly** [comment]
> 2 т.р.
от 500
да! 2500р
1000

Это блокировать запрещено

> Внимание Госпожи дорого!

Это блокировать можно/нужно

**Comment by inquisitor6789** [comment]
Все в ваших руках :-)
