### ISSUE TITLE
непонятки с техническим логом

### ISSUE THREAD

**Issue by inquisitor6789** [tebaly/freedomsex#174]
http://freedomsex.net/userinfo/profile/?id=5040613
![image](https://cloud.githubusercontent.com/assets/19651618/16515555/44e1b52c-3f7b-11e6-93bb-6de8d50cfdcb.png)

интересно, какой же я спам рассылал? Что за бред? Мамой клянусь, что все сообщения были уникальными :-)

**Comment by Fenslau** [comment]
Дык поди стандартные сообщения для журения модеров отправили парочку.

**Comment by inquisitor6789** [comment]
какие же они стандартные? ничего подобного. могу переписку скинуть если не веришь :-)

**Comment by tebaly** [comment]
@inquisitor6789 напишите на почту, я вам отвечу :)

**Comment by Fenslau** [comment]
Хех, я понял. Это если ссылку шлешь в сообщении - вот тебе и спам.

**Comment by tebaly** [comment]
@Fenslau не пали контору :simple_smile:
