### ISSUE TITLE
Количество жалоб

### ISSUE THREAD

**Issue by Fenslau** [tebaly/freedomsex#179]
Итак, когда-то было предложено отображать количество жалоб от разных пользователей (не суммировать жалобы от одного и того же), с такой целью чтобы пользователь не возглавлял топ, если кто-то пол-переписки на него скинул.
Похоже, это так и не было реализовано, тем не менее кое что всеравно не понятно

http://sexoo.ru/userinfo/profile/12581369 - и всё от одного пользователя, написано 6...
http://sexoo.ru/userinfo/profile/9643858 тоже все от одного, но написано 3

**Comment by tebaly** [comment]
> Похоже, это так и не было реализовано

А так и есть. Issue(проблема) ведь ещё открыта. После реализации даётся комментарий и проблема закрывается.

Вероятно вы о #70 - Там обсуждение повисло. Там было предложение "считать" и не было "отображать" - это хоть и похожие, но разные предложения. Давайте продолжим там, если вы действительно имели в виду тот тикет.
