### ISSUE TITLE
блокирование анкеты

### ISSUE THREAD

**Issue by Fenslau** [tebaly/freedomsex#195]
Сегодня столкнулся с таким случаем:
http://sexoo.ru/userinfo/profile/?id=12867761
Не смог понять, как анкета оказалась заблокированной практически мгновенно?

**Comment by tebaly** [comment]
А вам зачем?

**Comment by Fenslau** [comment]
Действительно, зачем ) Так, от нечего делать поинтересовался ) Считаете что мне это незачем знать? Скажите почему и я больше не побеспокою.

**Comment by tebaly** [comment]
Если система сработала штатно, зачем вам знать как именно? Учитывая что ответ лежит в плоскости, непосредственно прилегающей к ядру системы безопасности? 

А ещё, GitHub публичный сервис. Спамер, зная принципы работы СБ легко устроит атаку на сервис. В своей работе мы руководствуемся "Уставом параноика", первая заповедь которого - "Не доверяй никому". Это простой принцип безопасности.

Если возникает проблема в работе сайта, мы всегда благодарны за помощь в обнаружении или устранении такой проблемы.
