### ISSUE TITLE
Функционал исключения спора модераторов/администраторов

### ISSUE THREAD

**Issue by mj4444ru** [tebaly/freedomsex#2]
Предлагается запретить модератору/администратору выносить повторное одинаковое решение по жалобе. 
Либо сделать в арбитраже голосование, где необходимо минимум 2 голоса модератора/администратора для принятия решения.

**Comment by tebaly** [comment]
> Либо сделать в арбитраже голосование, где необходимо минимум 2 голоса модератора/администратора для принятия решения.

Хорошая идея! Поставить лимит по планке рейтинга принявшего ранее решение. Этож замечательно! Спасибо за идею ;)

Это конечно не то что вы предложили, но тоже метод. Такой подход используется в других системах контроля доступа, но несколько в иной плоскости, я об этом читал, но не знал куда всунуть. Вот сюда и всунем))

-- Описание - нужно додумать ---

- После принятия решения, решению приписывается значение рейтинга модератора/администратора который вынес решение.
- Если рейтинг модератора/администратора ниже того значения, что записано в решении, он не может его сбротить(!) **applausus**
- Сброс может сделать только администратор с большими привилегиями :)

---

Добавить возможность администратору вынести решение одновременно со сбросом, или вместо сброса в арбитраж. С занесением _значения рейтинга_ в историю решения

**Comment by tebaly** [comment]
Подключайтесь. 
Продумайте идею с "голосами" и попробуйте оформить ее до конца. Набросайте дизайн Юзер Интерфейса, расчертите постранично, подумайте над реализацией данного сервиса. Я прикинул "образно" - идея интересная, но сложно реализуема. У мее есть логичный предел и как следствие, ваша идея лишь мнимый выход.
 
Смотрите, **модель один**: вы предложили учитывать мнение 2 модераторов(_коэффициент_ = 2) против одного. Как следствие, данное решение направлено в смоделированных ситуациях против ОДНОГО человека(A). Тем самым, как выход, вы предложили ДВА голоса(X+Y). Предположим вы имели в виду свой голос(X), плюс дополнительный(Y). Противопоставление [1] : [1 + 1]. Но это имеет известный и очень малый предел.

Вы забываете в данной модели про само СООБЩЕСТВО, а что это значит? **Модель два**: То что у человека (А) может быть друг/единомышленник (B, C, ...). Тогда, ваши 2 голоса могут занять люди (B+C) - в данном случае ваше мнение будет не только в меньшинстве, оно станет в ТРИ раза меньше "учитываемым", чем в первой модели. Противопоставление [1 + 1 + 1] : [1].

Отбросив детали, придется увеличивать _коэффициент_ до 3, 4, 5 ... (∞) при этом мы начинаем меряться не только пипирками, но и их количеством в каждой команде. Это не есть сообщество, сообщество должно быть едино.

**Comment by tebaly** [comment]
Отсечка по рангу даст какую-то передышку в бесконечных спорах. Можно срезать этот лимит с учетом времени, например. Когда по истечении некоторого периода, решение снова можно будет оспорить. 

Как я вижу, вся система довольно сносно функционирует, проблема пока лишь в "спорах", которую мы заочно решаем лимитом "последнего слова". Отчасти это правильное, и довольно логичное решение. 

Мы с вами затрагиваем фундаментальные вещи. А именно. 
- Центализованные системы ограниченны и малоподвижны
- Децентализованные системы крайне импульсивны 

Плюс централизованной системы в крайне БЫСТРОМ принятии решения и распространении ПРИКАЗОВ. Децентрализованные системы строятся на СОГЛАШЕНИЯХ - при этом в них скорость распространения информации и принятия решений МИНИМАЛЬНА. Именно споры и "обсуждения" делают их такими тупыми. И чем больше сообщество, тем медленнее оно "думает", что часто приводит к его полному ПАРАЛИЧУ.

"Приказы не обсуждаются" - это в централизованных формах управления. И это отчасти круто, но имеет кучу недостатков. НО, они в чистом виде существуют давным давно и распространены, а децентрализованные системы крайне РЕДКИ - из-за того, что когда нужно принять быстрое решение, они беспомощны, начинается ХАОС и ПАНИКА - сообщество разбивается на противоречащие части.

**Comment by tebaly** [comment]
У централизованной системы всегда есть ЦЕНТР который имеет статус "последнего слова". Вы опять же обращаетесь к администрации и разработчикам за тем самым "последним словом". 

Полностью децентрализованные системы НЕ жизнеспособны. Именно поэтому распространение и получили гибридные системы в виде "пседо сообщества". Они на самом деле крутые, так как совмещают положительные качества обоих систем. И в этом направлении стоит двигаться. Что это значит?

Нам пора задуматься о создании биполярной системы. В которой есть глобальное сообщество и администраторы сообщества. Только в самОй верхушке стоит строить иерархию по принципам централизованных систем. И именно "отсечка" по рангу  превращает бывшее сообщество в псевдо-централизованную систему - это на самом деле интересно. Ведь нам как то нужно получить "последнее слово". Вопрос в том, кому это поручить и как? То что это должен быть именно **ОДИН** человек, очевидно.

**Comment by tebaly** [comment]
В данном смысле ОДИН не равно единственный. У нас есть много администраторов и все они равны. Просто без "обнуления рейтинга" мы имеем БЕСКОНЕЧНЫЕ споры/сбросы решений - так как тут ограничивается всё лишь упрямством человека. А при наличии возможности "заткнуть" не верного, получаем ДИКТАТ.. зато споры решаются просто и БЫСТРО - это из централизованной системы уже.

**Comment by mj4444ru** [comment]
Я всё думаю на эту тему.
Вы придерживаетесь мнения что в спор входить не надо, пусть останется как есть, но тут есть такие печальные стороны:

1. Последнее слово в споре это - Прецедент
2. Может пострадать невинный человек

В итоге предлагаю реально подумать даже не над ограничением споров, а её корректной многополярной реализацией.

Спор может возникнуть на следующие темы:
- Блокировать / Не блокировать
- Вирт / Не вирт / Накзать / Блокировать
- Понижение рейтинга администратора

Предлагаю следующий алгоритм ограничений:

**Блокировать / Не блокировать**
- Администратор может отправить заявку только один раз. Если его заявку отменили, повторно он отправить заявку не может (в случае если причина блокировки есть, заявку может отправить другой администратор который ранее не отправлял заявки по этой анкете).
- Администратор может отменить заявку только один раз (если кто то отправил её повторно, отменить заявку может любой другой администратор который ранее не отправлял заявку).
- В случае если поступила новая жалоба или замечание на человека, история подачи и отмены заявок обнуляется.

**Вирт / Не вирт / Накзать / Блокировать**
- Отправить заявку в арбитраж может любой модератор с рангом не ниже ранга вынесшего решение модератора.
- Вынести решение в арбитраже может любой модератор с рангом не ниже ранга модератора отправившего решение в арбитраж.
- Модератор не может повторно отправить заявку в арбитраж.
- Модератор не может повторно вынести решение в арбитраже.
- В случае вынесение заявки в арбитраж после решения администратора (особо тяжёлый случай который порождает Прецедент), для принятия решения необходимо не менее 3 голосов администраторов в одну сторону, причём 2 противоположных уже есть (если три администратора сговорились, это уже мнение сообщества).
- Невозможно отправить заявку в арбитраж, если было голосование администраторов по ней. Можно даже создать отдельный список таких голосований "Прецеденты" и в дальнейшем в случае отправки похожей заявки в арбитраж, указывать ссылку на Прецедент. Список таких заявок могут видеть все кто имеет право вынесения решений в арбитраж.

**Понижение рейтинга администратора**
- Мгновенно временно понижать рейтинг можно только за многократные неверные решения по заявкам, которых должно быть например более 30%. Ни за какие споры, ни за какие блокировки/аннулирования блокировок анкет блокировать нельзя. Этот запрет должен быть на уровне системы. То есть кнопочка блокировки доступна только если система зафиксировала превышение неверных решений. Временное понижение рейтинга всегда осуществляется до 0. Далее создаётся заявка на понижение рейтинга путём голосования. После голосования выставляется рейтинг по результатам голосования.
- Понижение рейтинга возможно созданием заявки на понижение путём голосования.
На голосование выносится решение понизить рейтинг. Не менее 3-4 администраторов должны предложить свою меру пресечения, то есть до какого значения они хотят опустить рейтинг (от -100 до текущий рейтинг). Голосование должно идти не менее 24 часов. По итогам, если равное количество или большинство не захотели понижать рейтинг, заявку аннулируем. Если большинство решило понизить рейтинг, берём среднее значение большинства. В течении голосования можно менять свой голос, величину понижения и свой комментарий относительно этой заявки.

**Comment by tebaly** [comment]
Благодарю за рассуждение и идеи. Прежде чем двигаться, необходимо принять фундаментальное решение. Существуют как минимум:
- Централизованные системы
- Децентрализованные
- Гибридные

https://ru.wikipedia.org/wiki/%D0%A2%D0%B5%D0%BE%D1%80%D0%B8%D1%8F_%D1%83%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F
http://vvy.me/gosi/toau/43.html
http://managment-study.ru/ponyatie-i-osobennosti-centralizovannoj-i-decentralizovannoj-sistem-upravleniya.html

Мы решили двигаться в сторону гибридной системы, при которой в начале пирамиды управления взаимодействия _децентрализованы_, но с каждым уровнем вверх, система обретает некие _узлы управления_ "администраторы". С дальнейшим ростом уровней, среди администраторов появляется _иерархия_.

Вот в части _иерархии_ на данный момент ничего не придумано, но путь к её реализации намечен. Почему? Потому как например вы, в данный момент, обращаетесь к разработчикам, как к высшему звену в иерархии, имеющему максимум полномочий. Так вот, нужно разработать систему, в которой топ формируется автоматически, без участия администрации и разработчиков, в котором ни разработчиков ни администрации нет вообще. Но высший элемент присутствует.

**Comment by mj4444ru** [comment]
Я прочитал всё что вы прислали.
Вы очень странно перемешиваете автоматизированное управление с ручным управлением, а так же управление разнородных структур. А если в общем, то через чур всё усложняете (в теории).

**В нашем случае есть:**
- Задачи по соблюдению правил и порядков в рамках самоуправляемого сообщества.
- Проблемы и недостатки связанные с некорректным поведением некоторых его участников.

**Задача:**
- Разделить принятие решений по уровням на основе опыта участников
- Решить проблемы связанные с неоднородностью решений

Вы очень хотите сделать систему сверху централизованной, непонятна цель. У нас грубо говоря всего 2 задачи, просто с разными уровнями ответственности.
Первую задачу решают модераторы, а их решения могут менять администраторы.
Те же люди, но в ряде случаев путём голосования.

**Минусы вашего предложения:**
- Человек с наивысшим рангом начинает диктовать свои правила - это уже не сообщество
- Справедливость решения зависит не от наиболее адекватного участника, а от задрота который умудряется угрожать другим участникам (недавно уже ранее известная личность отправила решение в арбитраж и вынесла противоположный вердикт не смотря на то что 8 модераторов и администраторов единогласно разрешили разрешить, а так же трижды отправил заявку на блокировку, не смотря на то что другие администраторы изначально не стали блокировать, в потом два разных администратора отменили его решение).
- Результат данного варианта отсутствие конфликтов, но при этом не повышается качество и адекватность их решения...
- Будет стимул для накручивания рейтинга чтобы быть главным (что так же будет стимулировать рост неверных решений).
- Уже сегодня механизм понижения (действующий по рангу) приводит к тому что администратор начинает угрожать своими возможностями. А будет ещё хуже...

Теперь назовите недостатки моего предложения (не считая значительно более сложной реализацией)...

Теперь отдельно хочу вернуться к последней ссылки:
> - число решений, принимаемых на каждом уровне управления;
В этом плане я считаю что текущая система почти идеальна.
> - важность принимаемых решений для организации;
В этом плане я бы тоже ничего менять не стал.
> - степень контроля за исполнением принятого решения.
Вот тут возникают проблемы, так как на сегодняшний момент система имеет серьёзные недостатки в виде равных прав всех администраторов и модераторов, а так же возможных превышений полномочий администраторами, которые с другой стороны отобрать совсем тоже недопустимо.

**Comment by tebaly** [comment]
> Теперь назовите недостатки моего предложения 

Значительно более сложная реализация :)

> Будет стимул для накручивания рейтинга чтобы быть главным (что так же будет стимулировать рост неверных решений).

Мы с вами забыли о механизме "резиденты" - его развитие было приостановлено. Согласно этой концепции, из числа активных администратором назначаются "резиденты" - их рейтинг не изменяется, а фиксирован на максимальном уровне. Это как раз те люди, которые являются "последним словом" - понизить рейтинг друг другу они никак не смогут.

Это как раз должно будет решить проблему "наиболее адекватного участника", я думаю.

> Уже сегодня механизм понижения (действующий по рангу) приводит к тому что администратор начинает угрожать своими возможностями. А будет ещё хуже...

Надеюсь у нас получится решить и эту проблему

**Comment by tebaly** [comment]
https://geektimes.ru/post/274234/

Очень хорошее мнение по поводу различия "демократии" - **мнения большинства** и экспертной оценки. Вся публикация интересна в целом, а не только этот абзац.

> Это очень плохо. Да, эксперты тоже могут ошибаться: примеры со взрывом Челленджера или Талидомидовая трагедия печально напоминают нам об этом. Но в общем случае, эксперты все же лучше некомпетентных людей: доктора, не смотря на все их ошибки, справляются с лечением большинства болезней лучше, чем духовные целители или ваша бабушка с ее особенной припаркой из куриных кишок. Отвергнуть понятие экспертного знания и заменить его ханжеским требованием защиты права каждого на свое собственное мнение — глупо.

**Comment by mj4444ru** [comment]
**По поводу статьи:** посмеялся... Конечно многое там верно замечено, но в политике этот человек совсем ничего не понимает... Видимо в чём то другом эксперт... Да и роль экспертов в данной ситуации я перекладываю на высший на сегодняшний день ранг администраторов, что подразумевает решение вопросов именно Экспертами, а не дилетантами.

**По поводу его выводов:** Ну в общем верно подмечено, но мало имеет отношение к нашей ситуации...

**По поводу резидентов:** Да, им тоже надо как то договариваться. Вопрос как? Вот вышеупомянутый товарищ договаривается исключительно угрозами и сбросом рейтинга. Так же жёстко он ведёт себя в отношении всех остальных при принятии решения. И именно он будет в числе экспертов резидентов.

Теперь про вашу отсечку по рангу (которая сейчас определяется не адекватностью эксперта, а тому сколько времени он уделяет этому ресурсу):
Недавно слушал один интересный разговор двух студентов: и суть такова, один рассказывает другому как прошла конференция по выбору стратегии развития и закупок материалов для гос нужд. В том числе была затронута тема выбора материалов. Выбор стоял между композитными и обычным металлом. Не смотря на то что у металла нет ни одного плюса по сравнению с композитными материалами, был выбран металл, лишь по тому что за его эксплуатацию выступили доценты (старики с СССРовскими корочками), видите ли они умнее студентов. Слушали это дело наш гор.совет, ввиду полного отсутствия знаний по теме, полагаясь полностью на корочку доцентов). Конечно то что все поставки метала осуществляются через фирмы, владельцы которых те самые доценты это совпадение, но сути это не меняет.

По этому по прежнему считаю что возможность ДОГОВАРИВАТЬСЯ необходимо ИСКЛЮЧИТЬ!
Использование ранга который строится на основе активности так же ИСКЛЮЧИТЬ!
Администраторы не хотят идти на конфликт и по этому не считают нужным вмешиваться в ситуация, в виду этого надо исключить механизм давления на администраторов в виде понижения рангов (сам механизм при этом необходимо оставить).

**Comment by tebaly** [comment]
> По поводу резидентов: Да, им тоже надо как то договариваться. Вопрос как?  

Так диалог же. Если вы сбрасываете решение, вы МОЖЕТЕ подробно описать причину. В случае, если ваше решение/действия может вызвать "вопросы" - подробная аргументация в ваших же интересах. 

Администратор ("эксперт") - вправе не давать объяснений если на 100% уверен в правильности своих действий, но, если вопросы могут возникнуть и к нему с нашей стороны, в его интересах также дать комментарий к действию.
--
Диалог возможен лично - либо в сообщениях, либо по телефону, либо в скайпе, либо при личной встрече. Диалог возможен в любой ситуации. В ваших силах его начать, в ваших силах его контролировать. Важно - не конфликт, ругань и перепалки, а спокойный и аргументированный диалог.

По части решений и "арбитража" мне кажется всё предельно работоспособно на данный момент. Чуть допилим и понаблюдаем, как это далее скажется на обстановке.

**Comment by tebaly** [comment]
Введено ограничение при сбросе решений. Задействована иерархия от уровня достижений. Также возобновлена работа над идеей резидентов. Резиденты в данный момент назначаются вручную,  исходя из рекомендаций администраторов Сообщества, либо на основании оставленных ранее заявок. В зачет идут достижения, стаж отсутствие серьезных разногласий и тд. У каждого администратора свои требования. 

Спасибо.
