### ISSUE TITLE
Интим фотографии

### ISSUE THREAD

**Issue by mj4444ru** [tebaly/freedomsex#20]
Необходимо не прятать интим фотографии за ширму, а скрывать их за надписью что это интимная фотография. Если пользователь нажал на "Показать", он подтверждает что он согласен увидеть интимную фотографию в не зависимости от того что там.

В случае отправки интимной фотографии без соответствующего признака и поступлении жалобы, все существующие и будущие фотографии пользователя скрытно автоматически становятся интимными в независимости от установок.

**Comment by tebaly** [comment]
> будущие фотографии пользователя скрытно автоматически становятся интимными в независимости от установок
На данный момент всё так и работает, несколько иначе, но какие бы он фото не отправил, они будут отмечены "интим". 

> Необходимо не прятать интим фотографии за ширму
Есть ли принципиальная разница? На данный момент реализовано более интуитивно и понятно для пользователей. Сразу видно что прислано фото. И частично можно сделать вывод, стоит ли смотреть на оригинал фото.

**Comment by mj4444ru** [comment]
1) Всё равно на уровне правил сайта надо запретить отправлять интим фотографии без разрешения.

2) Но чтобы этот запрет работал, надо придумать способ наказания в интерфейсе администратора.
Сейчас когда человек нажимает пожаловаться на фотографию, непонятно в начале беседы отправил, или в процессе.
Как вариант писать кроме давности фотографии, количество сообщений собеседника (получателя фотографии) на момент отправки жалобы. Если будет 0, то сразу понятно, человек отправил отправил без разрешения. Сейчас поступают жалобы, но с одной стороны и принять надо бы, а с другой стороны оснований верить жалобе тоже нет.

**Comment by tebaly** [comment]
#### "Запретительный" путь, не наш путь.  
Фактически отправка таких фото без согласия собеседника запрещена. Таким образом, имея жалобу на фото, и если фото не "фейк" - значит оно было отправлено "без согласия" получателя, всё просто. Таким образом пользователя можно наказать за подобное поведение.

**Конституция РФ, Статья 23:**
>1. Каждый имеет право на неприкосновенность частной жизни, личную и семейную тайну, защиту своей чести и доброго имени.

>2. Каждый имеет право на тайну переписки, телефонных переговоров, почтовых, телеграфных и иных сообщений. Ограничение этого права допускается только на основании судебного решения.

Таким образом, мы фактически не имеем права что-либо запрещать в переписке. Нам **поступают жалобы от получателей на отправителей** с приведением текста и содержания сообщения отправленного пользователю. По данной жалобе мы можем принять решение, соответствует ли поведение пользователя правилам сайта.

**В отсутствии жалоб**, в соответствии с Конституцией РФ и множества других стран, отправитель вправе отправить получателю что угодно _"Ограничение этого права допускается только на основании судебного решения."_ И, если это является желанным со стороны собеседника, он НЕ отправит жалобу на отправителя, и мы с вами никогда об этом не узнаем. Если жалоба есть - значит нарушение имеет место быть.

При этом. Нарушение имеется по части "отправлено то, чего не желает получать собеседник". Иных запретов у нас нет и не ожидается. Таким образом, общение организовано в рамках действующего правового поля, и ни Конституции ни иных законов не нарушает. Все права пользователей сохранены. Мы с вами просто **не имеем права запрещать** отправку чего либо.

**Comment by mj4444ru** [comment]
По первому пункту: На самом деле я имел ввиду на уровне правил сайта. Я зашёл в отправку фотографии, там достаточно подробно и понятно написано всё что я имел ввиду, так что это уже на самом деле сейчас есть.
По второму пункту всё таки было бы полезно что то подобное сделать в любом варианте.

**Comment by tebaly** [comment]
Планируем данную фитчу для всех жалоб.
