### ISSUE TITLE
Ограничения для арбитража

### ISSUE THREAD

**Issue by mj4444ru** [tebaly/freedomsex#23]
Человек с меньшем уровнем доступа не может отправить решение в арбитраж.

**Comment by tebaly** [comment]
- Меньшим относительно чего?
- Чем именно вызвана данная потребность?

**Comment by mj4444ru** [comment]
Если решение в арбитраж отправил модератор 10 ранга, модератор 1-9 ранга это решение рассмотреть не может.

**Comment by tebaly** [comment]
Ну это же мы уже с вами приняли как основу решения - "отсечка по рангу" плюс временной лимит - схема при которой "отсечка по рангу" будет действовать лишь некоторое время. После истечения интервала времени решение снова можно будет направить на арбитраж тем, у кого рейтинг ниже.

**Comment by mj4444ru** [comment]
Подробнее я описал тут
https://github.com/tebaly/freedomsex/issues/2
