### ISSUE TITLE
Особое наказание

### ISSUE THREAD

**Issue by mj4444ru** [tebaly/freedomsex#30]
Предлагаю запретить особое наказание свыше 40-60...
Для анкет подлежащих блокировке выше 20-30...
Иначе товарищ Сергей топит за 100 и блокировка уже перестаёт иметь смыл...

**Comment by tebaly** [comment]
Ок. Верно.

**Comment by tebaly** [comment]
Тут дело в следующем. У сообщества нет инструмента мгновенной перманентной блокировки. Возможность его реализации изучается. До того, в качестве этого инструмента негласно выступает "перебор по наказаниям" - что де факто блокирует деятельность вредителя.

**Comment by mj4444ru** [comment]
нет, это совсем не так... блокирует возможность отслеживать вредителя, но не действия вредителя (так как он просто создаст новую анкету)...

**Comment by inquisitor6789** [comment]
Я вижу тут меня помчнули в суе. И не надо грязи, больше 80 не выдаю. 
Что же касается самого механизма, то как по другому пресечь нарушения пока не сработпоа блокировка? Особенно это касается секса за деньги.
Хотя это тоже не панацея, т.к. подозреваю, что в большинстве случаев делается массовая рассылка

**Comment by tebaly** [comment]
![kiss](http://cs.pikabu.ru/images/big_size_comm/2013-05_1/13677338063675.jpg)

```
Минутка юмора :satisfied: 
```
