### ISSUE TITLE
Показ фото в виде спойлера

### ISSUE THREAD

**Issue by wWolfovich** [tebaly/freedomsex#31]
Сделайте пожалуйста чтобы фото вместо того чтобы закрывались "фруктами" сворачивались в так называемые спойлеры, в том числе и в первую очередь свои же фото.. А то частенько сиху на сайте с работы и обмениваюсь интим фото, палево же :)

**Comment by tebaly** [comment]
При более глубоком приближение, добавление "клика" сделает не совсем ясным интерфейс. Так как самого фото "не будет видно" некоторые пользователи просто не поймут, что им вообще пришло фото. Текущая реализация хотя бы позволяет понять этим пользователям, что им вообще пришла какая-то фотография. Это позволяет им больше сконцентрироваться на поиске того, как это фото просмотреть без "фруктов", то бишь найти ссылку/кнопку "Показать".

Это мы с вами всё могём понимать, а кто-то даже про **емаил** слышит _впервые_ :(

**Comment by wWolfovich** [comment]
Ну во-первых заголовк спойлера можно сделать не таким мелким. И типа "Я ФОТО, НАЖМИ МЕНЯ ЧТОБ ПОСМОТРЕТЬ". Ну или нахудой конец, если уж пометил фото интимным, то оно должно быть прикрыто спойлером либо "фруктом" без разницы мое оно или собеседника.

**Comment by tebaly** [comment]
"ДА КАКОЕЖ ТЫ ФОТО?. ТЫЖ КНОПКА! А ГДЕ ФОТО?.." Но ведь некоторым нравится собой любоваться) Зачем их лишать такого удовольствия?)

По поводу "скрывать своё фото" вы изначально не говорили. Тут уже тема дискуссии..
- От кого прятать свои фото?

Задумка была не в том, чтобы прятать фото от находящихся с вами рядом людей (как например спрятан пароль за звездочками/точками) а чтобы собеседника не шокировало присланное фото, либо шокировало в меньшей степени.

В общем и целом ваш посыл понятен. Ну не подразумевалось использование сайта в общественных местах.. 

Возможно мы и не везде следуем правильным принципам, но есть такая вещь - _S_OLID а в нем S как SRP(Single responsibility principle) - Принцип единственной обязанности. В частности, если определена обязанность "уменьшить негативные эмоции", то должна быть реализация направленная только на это.  Навешивание новых обязанностей, как например предложенной вами "я же тут не один", нарушит такой принцип. SRP это больше из кода конечно, но на практике оправдан и в дизайне интерфейса.

**Comment by tebaly** [comment]
Попробуем учесть ваши пожелания при обновлении интерфейса сообщений/диалогов. 
Спасибо.
