### ISSUE TITLE
Пол человека в адмике

### ISSUE THREAD

**Issue by mj4444ru** [tebaly/freedomsex#36]
В анкете у девушки
Предложил 0, принял 40 знакомств 
Сделайте что бы у девушек было
ПредложилА 0, принялА 40 знакомств

**Comment by inquisitor6789** [comment]
А надо ли? Все таки анкета пользователя (слово мужского рода) и это атрибут пользователя.
Лучше бы пол выводить. А то последнее время много Саш и Жень развелось. И чтобы понять фейк или нет приходится открывать анкету. А с мобилы это не очень удобно

**Comment by tebaly** [comment]
Замечание верное. Относится к улучшениям. Поправим обязательно. Это больше не анкета, а профиль нарушителя, если смотреть глубже - нарушитель отправил и принял. А так, там есть в части UI огрехи в том плане, что не всегда понятно, какой пол у нарушителя..
