### ISSUE TITLE
статистика модератора

### ISSUE THREAD

**Issue by inquisitor6789** [tebaly/freedomsex#39]
Заметил, что если человек не является модератором, то у него все поля статистики пустые, а вот поле "Сброшено в арбитраж" заполнено.
Пример - http://freedomsex.net/argue/profile/11794114
Это баг или фича?
Или это проявляется только на не модераторах?

**Comment by mj4444ru** [comment]
так там вроде всё логично... что не так то? график разве что ещё не нарисовался, так подозреваю данных мало...

**Comment by inquisitor6789** [comment]
да, по указанной ссылке уже все ок.
проблему я заметил если человек еще не модератор.
наверно можно забить на это

**Comment by tebaly** [comment]
> если человек еще не модератор
Скорее это фитча, нежели баг. Так как статистическая информация может быть использована не только с благими намерениями. Я уже не помню как там и что, но вроде как есть какой то лимит на доступ у статистике модераторов "набирающих" рейтинг.
