### ISSUE TITLE
Глобальный лог/свод правил.

### ISSUE THREAD

**Issue by tebaly** [tebaly/freedomsex#41]
Предлагается создать/разработать список правил по номерам/пунктам на основе:
- постов справки/блога
- соглашений Сообщества

Расположение: в корне сайта
Название: rules
Формат: .txt (.md или любой другой)

https://github.com/tebaly/freedomsex/blob/dev/rules.txt

**Comment by tebaly** [comment]
Изменен формат с текстового(txt) на разметку .MD

Важные замечания в новости [Глобальный список правил](https://github.com/tebaly/freedomsex/blob/dev/doc/news/10602016-1.md)

**Comment by inquisitor6789** [comment]
большой вопрос на счет

11.2. Если некоторые пункты правил перекрываются законодательством страны Пользователя, и разрешают запрещенные правилами поведение, общение или действия, такое поведение, общение или действия может считаться разрешенным.  


считаю, что не совсем корректно ссылаться на законодательство другой страны.

1. надо знать язык этой страны, т.к. все законы будут написаны на этом языке
2. надо еще знать страну. В текущей реализации это затруднительно. Какие-нибудь Большие Мудища могут быть в нескольких странах и не в одном экземпляре.

**Comment by tebaly** [comment]
Это не для обвинения
1.4. Для защиты Пользователя Администратор вправе предоставить юридическое обоснование отсутствию нарушений Пользователем законодательства, если другие Администраторы считают иначе.

То есть, если кто-то вкурсе того, что "это" законно и может это обосновать - флаг в руки :) Мы с вами не можем ограничивать Граждан в их законных свободах. Ну, не во всех))

**Comment by inquisitor6789** [comment]
чисто гипотетическая ситуация, в плане бреда и режима максимальной паранойи

юзер1 из Голландии, юзер2 из России. Насколько мне известно, то в Голландии употребление марихуаны разрешено для резидентов. Юзер1 предлагает Юзеру2 накуриться и нажраться грибов. Причем сделать это совместно (в данном случае не важно где). В России есть статья 230 УК (Статья 230. Склонение к потреблению наркотических средств, психотропных веществ или их аналогов).
Как в этой ситуации быть? По хорошему надо банить Юзера1. Но согласно законам Голландии это не воспрещается (точно не уверен, но скорее всего это так). И тут вступает в действие пункт 11.2

**Comment by tebaly** [comment]
Читаем внематочно :grinning:
1.3. В случае, если собеседник и Пользователь находятся в разных странах, законодательство одной страны перекрывает законодательство другой с приоритетом запрещенных действий.

То есть - банить обоих :) ну или того, кто из РФ

**Comment by tebaly** [comment]
> В России есть статья 230 УК (Статья 230. Склонение к потреблению наркотических средств, психотропных веществ или их аналогов).

Вы не обязаны этого знать)) меньше знаешь, крепче сон :blush:

**Comment by tebaly** [comment]
Как минимум мы с вами не имеем права решать что законно, а что нет. Для этого должно быть постановление суда. Если его нет, то пользуемся этим правилом при крайней необходимости. Как-то так.

Здесь применимы нормы в части 
* Незаконное содержание

1.1. Незаконным может быть принято содержание по факту являющееся законным, если оно имеет те или иные признаки незаконности.
1.2. Ни администраторы ни модераторы сайта не обязаны иметь юридического образования, для правильного толкования законности содержания сообщений.
1.3. Администраторы руководствуются собственными знаниями по части законности содержания сообщений, в принятии решения о наказании Пользователя или блокировании анкеты.
1.4. В некоторых случаях Администраторам рекомендуется избегать перегибов, в иных рекомендуются упредительные воздействия.
1.5. Некоторые скользкие темы, такие как зоофилия, инцест, интимные сцены с участием несовершеннолетних, детей, родственников, сцены насилия - употреблять в общении крайне нежелательно. Жалоба на подобное содержание может привести к блокированию анкеты Пользователя или наказанию.
1.6. В сложных случаях Администраторы принимают решения совместно.

**Comment by tebaly** [comment]
В таких случаях вы вправе "перебдить чем недобдить". Есть и другие, где перебдить "не нужно". В общем и целом, тема скользкая. 

Если принципиально важно, то
* Решение принимается только при наличии постановления судебной инстанции страны проживания Пользователя.
* И никак иначе :)

**Comment by mj4444ru** [comment]
давайте все жалобы в суд передавать, пусть они решают...

я думаю у нас должны быть свои правила и моральные нормы...

но опять же, для блокировки не достаточно жалобы или замечания...
а вдруг пользователь сначала ему разрешил писать ему подобное, а потом пожаловался (провокация) ?
предлагаю в случае серьёзной жалобы на блокировку таких личностей требовать полной истории для адекватного решения...

**Comment by tebaly** [comment]
> давайте все жалобы в суд передавать, пусть они решают...

Не все. А конретно те, которые принципиальна в юридическом плане. Трактовка правил сейчас такова, что вы можете блокировать Пользователей при малейшем намеке на _незаконное содержание_
* Блокировать нужно только в случае крайней на то необходимости

Например помню случай, когда кто-то зацепился за _сепаратистское_ содержание жалобы - это лишнее, как и тема при _грибы_. У нас не тот формат
* Главнейшая цель администрирования, противодействие (а)_индивидуалкам_ и интим услугам, (б) мошенникам и мошенническим схемам, (в) спамерам с массовыми рассылками
* Остальное как мне кажется сугубо по вашему желанию, и к этому не нужно сильно придираться, такой принципиальной задачи не стоит

В соответствие с главным юридическим документом проекта
> 7.2. Администрация Сайта не занимается предварительной модерацией или цензурой информации Пользователей и предпринимает действия по защите прав и интересов лиц и обеспечению соблюдения требований законодательства только после обращения заинтересованного лица к Администрации Сайта в установленном порядке.

Администраторы и модераторы во-первых не обременены юридической ответственность, во-вторых, Администраторы и модераторы приравнены к администрации сайта, посему
* в соответствии с пунктом 7.2. _Соглашения о предоставлении услуг_ вы имеете полное право забить на юридические аспекты до поступления официального обращения, в иных случаях, судебного постановления
* но мы естественно так не поступаем, и действуем _по мере необходимости_ самостоятельно
* меру необходимости также сами определяем
* просто без перегибов

**Comment by tebaly** [comment]
> разрешил писать ему подобное, а потом пожаловался (провокация) ?

Дабы ничего не усложнять и написаны правила, в соответствие с которыми, писать "такое" крайне не желательно

**Comment by tebaly** [comment]
> 1.1. Незаконным может быть принято содержание по факту являющееся законным, если оно имеет те или иные признаки незаконности.

У вас развязаны руки в плане блокирования по "законам". Мы просто просим не перегибать с этой возможностью тогда, когда в этом нет явной необходимости.

**Comment by tebaly** [comment]
Опять топик в оффтопик загнали :(
