### ISSUE TITLE
Сортировка жалоб в профиле нарушителя.

### ISSUE THREAD

**Issue by inquisitor6789** [tebaly/freedomsex#43]
Было бы не плохо сделать сортировку жалоб в профиле не по дате принятия решения, а по дате подачи жалобы или по дате написания (как это сделано для жалоб по которым решение не вынесено).
В 95% случаев текущая сортировка устраивает. Но остается 5% сложных случаев когда порядок  сообщений важен.

**Comment by inquisitor6789** [comment]
и еще по профилю....
похоже нашли способ обходить систему безопасности. Идет рассылка фото с расценками и условиями http://freedomsex.net/userinfo/profile/?id=11795678
не пора ли вводить модерацию жалоб на фото?

**Comment by mj4444ru** [comment]
да там вообще с датами беда (они неверные)
PS: и ссылка на администратора отменившего блокировку некорректная.

**Comment by tebaly** [comment]
Закрепляем
* по дате подачи жалобы или по дате написания

Возражений нет?

**Comment by inquisitor6789** [comment]
1. По дате подачи
2. Если дата подачи одинакова (сомневаюсь что возможно с точностью до мс), то По дате написания
Хотелось бы именно в таком порядке

**Comment by mj4444ru** [comment]
Сортируем по двум критериям:
- Вверху жалобы в статусе не принятого решения, далее все остальные
- По айди замечания по убыванию (там же автоинкремент?)

**Comment by tebaly** [comment]
Закрытые жалобы сортируются по _дате обновления_ 
* подразумевало удобство в том, что вверх попадают _измененные_ кем-то решения

> В 95% случаев текущая сортировка устраивает. Но остается 5% сложных случаев когда порядок сообщений важен.

Я сейчас меняю порядок. Не получится ли что
* в 5% хорошо, а в 95% было лучше?

**Comment by tebaly** [comment]
Порядок прямой или обратный?

**Comment by tebaly** [comment]
По очереди написания сообщений - порядок обратный (последнее вверху, первые внизу)

**Comment by Fenslau** [comment]
Сейчас как то так получилось, что непонято, правильно ли сработала сортировка:
http://sexoo.ru/userinfo/profile/?id=12325442 - профиль. 
Видим что жалоба про палку в жопу выше, чем про проверку парня. Хотя про парня была подана и принята недавно. Что же она более суток назад была подана и где то висела-болталась до сегодняшнего дня?

**Comment by tebaly** [comment]
**По очереди написания сообщений**
* теперь жёстко в той очередности, в которой они идут в переписке пользователей

Порядок обратный (последнее вверху, первые внизу)
* первые написанные сообщения находятся внизу списка
* только что, написанные совсем недавно, последние сообщения из переписке - наверху

Спасибо за обращение
