### ISSUE TITLE
Ошибка в профиле пользователя в админке

### ISSUE THREAD

**Issue by mj4444ru** [tebaly/freedomsex#54]
1. Некорректные даты в замечаниях.
2. Некорректная ссылка на администратора отменившего блокировку пользователя.

**Comment by inquisitor6789** [comment]
3. иногда случается, что некорректна ссылка на администратора опубликовавшего/отклонившего замечание

**Comment by tebaly** [comment]
Накидайте пожалуйста подробностей. Я попробую разобраться
* Некорректные даты в замечаниях - это дата обновления скорее всего

**Comment by tebaly** [comment]
Пожалуйста, кидайте по одной проблеме в обсуждение. Так удобнее) Спасибо за понимание

**Comment by tebaly** [comment]
* Некорректная ссылка на администратора отменившего блокировку пользователя.

Исправлено

**Comment by tebaly** [comment]
>"3. иногда случается, что некорректна ссылка на администратора опубликовавшего/отклонившего замечание"

#72

**Comment by tebaly** [comment]
> Некорректные даты в замечаниях - это дата обновления скорее всего

#73
