### ISSUE TITLE
История жалоб "ябеды" и "подсудимого"

### ISSUE THREAD

**Issue by Fenslau** [tebaly/freedomsex#56]
В общем, идея еще не полностью созрела, но тем не менее хочу описать ее, может быть кому-то она покажется интересной. Можно будет ее развить и дополнить.
Идея в том, чтобы избежать случаев, когда девушек провоцируют тролли и жалуются потом на каждое ее сообщение (при этом не каждое далеко из них проходит голосовку, но если хоть одно пройдет, она сразу оказывается в нарушителях с большим количеством жалоб). Предлагается перед вынесением окончательного решения "наказать" - иметь возможность просмотреть историю жалоб как на ябеду, так и на жертву. Можно это сделать опционально как-то, но чтобы такая возможность была. 
Иначе случаются ситуации, когда только уже после наказания смотрим в профиль девушки и обнаруживаем, что ничего там такого то и не было, довели тролли. Сегодня только пообщался с такой и убедился лично в ее адекватности. Но капчи то за наказание уже не снять.

**Comment by inquisitor6789** [comment]
вся фишка в том, что жалоба должна оцениваться без контекста беседы.
Даже если кто-то кого-то довел это не повод оскорблять кого-либо. От этого тролль только жирнее становится. Есть 2 хороших механизма - игнор и блокировка. От игнора тролли чахнут и худеют. Так же никто не мешает девушке написать жалобу и в подтверждение своих слов скинуть хоть всю переписку с троллем.
Доступ ко всем жалобам есть у админов. Так же есть адреса пароли и явки на тех кто жаловался.

**Comment by Fenslau** [comment]
Не повод, согласен. Но тролли то в этой ситуации однозначно казлы, а жертва - лишь уже по факту. Она может не подозревать, как правильно наказывать, не обратить внимание на эту опцию. Или просто не любительница ябедничать. 
А на сколько я знаю, доступ ко всем жалобам появляется уже после наказания, когда в истории можно посмотреть профиль того, кого наказали. Но даже при желании, капчи уже не снимешь. Если еще не накидают другие, пока она в активных. 
По поводу того, что жалоба должна оцениваться по факту, без контекста и субъективного мнения - согласен. Но может быть Тогда сделать сброс капч, если по итогам выяснилось, что оно того не стоило? Хотябы коллегиально, чтобы избежать всяческой протекции и т.п.
В принципе, я говорил, что идея не полностью назрела, но может что-то из нее полезное можно реализовать, как думаете?

**Comment by mj4444ru** [comment]
> вся фишка в том, что жалоба должна оцениваться без контекста беседы.
верно

> Даже если кто-то кого-то довел это не повод оскорблять кого-либо.
тоже верно

> в подтверждение своих слов скинуть хоть всю переписку с троллем.
В нашей стране большая часть населения не знает сколько будет 1/2 + 1/2 (вчера задал этот вопрос 3 студенткам физмата, не смогли ответить). Естественно сказать "сам дурак" проще чем грамотно составить замечание которое потом примут. У простых людей нет цели нагадить другим.

> Так же есть адреса пароли и явки на тех кто жаловался.
Хорошо бы что бы это было доступно без копипаста айдишников.

**Comment by mj4444ru** [comment]
> Тогда сделать сброс капч

Не надо без разбора всем подряд пихать капчи

**Comment by Fenslau** [comment]
Без разбора капчи пихать ни в коем случае нельзя. В принципе, я согласен, что одно необоснованное наказание и 15 капч (или сколько там), не сильно испортят общение девушке. Если она давно на сайте достаточно. Поэтому я сразу сказал, что идея довольно сырая и не просится в топы, как говорится. На данный момент, все что мы можем сделать - это остановить рост капч, если отметим как -ложно. Может быть этого недостаточно? В некотором случае, я считаю, должна быть какая-то возможность или не допускать спровоцированного наказания, или же отменить его последствия (без изменения самого факта и сброса его в арбитраж). Если пользователь давно на сайте, на него бывает что скапливается куча жалоб давнишних, где мы можем прочитать его сообщения и понять, как он обычно общается. И сделать вывод, что данный случай был скорее исключением. Но ведь бывает так, что кого-то спровоцировали весьма ловко, а истории нет, кроме этих провокаций.

**Comment by mj4444ru** [comment]
да, вы верно всё замечаете.
я давно с этим борюсь, но продвижений нет. и пока даже вариантов возможного решения тоже нет.
необходимо видеть переписку (частично или всю), а такую возможность нам дать не могут по понятным причинам.

а провокаторов всё больше и больше.

**Comment by Fenslau** [comment]
Переписку давать ни в коем случае нельзя! Я даже скорее за то, чтобы была возможность удалять явно необоснованные и давнишние жалобы, потому что бывает такое, что мы становимся свидетелями явно ошибочных жалоб, читая эту переписку, мы поступаем некорректно, так как становимся свидетелями того, чему бы не надо. Это происходит потому что часто жалуются по ошибке. Я против того чтобы такие "жалобы" хранились. Но как это сделать - ума не приложу.

**Comment by inquisitor6789** [comment]
С удалением по времени нет никакой проблемы. Как старые сообщения сейчас удаляются так же и старые жалобы будут удаляться. Только зачем это??? Какая разница обоснована жалоба или нет? И вы читаете ВСЕ жалобы в профиле? Даже те, которым пару месяцев? :-0

**Comment by Fenslau** [comment]
Как бы иногда это происходит ненамеренно. Известно, что ненамеренные жалобы поступают и будут поступать. Ну пролистываешь вниз - и вуаля - ты уже свидетель интимного момента в переписке, а жалоба была явно не намеренная. Вот тебе и тайна переписки. Я против такого. (не буду щас распространяться о том, что это порой интересно и пикантно).

**Comment by mj4444ru** [comment]
вы сильно приувеличиваете... это уже должно быть профессиональное... как гинеколог например... врачь каждый день смотрит на интимные месте и это норма... так и мы, должны быть привыкшие ко всему и чтение жалоб не так уж и страшно...
и я уверен что многие пользователи когда жалуются, готовы предоставить администраторам всю переписку...

**Comment by tebaly** [comment]
>  Вот тебе и тайна переписки

Тут дело в доверии к собеседнику. Если пользователь позволяет себе отправлять "интимные моменты" малознакомым людям, мы тут с вами причем, и чьи это проблемы?) А если этот малознакомый запостит скрины переписки в паблик ВК, на форчан, двач и тд. - кому от этого станет легче и кто в этом по сути то виноват? Можем ли мы с вами противостоять подобному поведению? То что содержание улетает в админку, это самое меньшее из зол. Пишется оно Пользователем собственноручно, а отправляется в админку (или на двач) его собеседником. Такое положение дел спасает проект от проституток, мошенников и спамеров. Проект анонимный, даже если в админке всплывают интимные детали, их сложно увязать с реальным человеком. А если это становится возможным, кто виноват?)

Множественные необоснованные жалобы "нивелируются/обесцениваются" системой автоматически, только никому об этом не говорите, это секрет ;)

**Comment by tebaly** [comment]
То, что кто-то позволяет себе оскорблять других пользователей, пусть даже в ответку, ничем их не оправдывает. Подобное поведение на сайте крайне не рекомендуется. Это не порок системы, это малограмотность и необразованность Пользователей. Этику общения в сети еще никто не отменял - будьте вежливы друг к другу, и такой проблемы как озвучено здесь, просто не будет существовать. Вы не согласны?)

**Comment by mj4444ru** [comment]
мы то все согласны...  вы это пользователям объясните...

а решение проблемы простое: не надо особое всем подрят не глядя давать...

**Comment by tebaly** [comment]
> решение проблемы простое: не надо особое всем подрят не глядя давать...

Это уже от нас всех с вами зависит. Можно это мониторить и "общаться" с теми кто перегибает, или перегибнуть им не спрашивая :)

**Comment by tebaly** [comment]
Считаю вопрос исчерпан
