### ISSUE TITLE
Особое наказание и модерирование сообщений

### ISSUE THREAD

**Issue by mj4444ru** [tebaly/freedomsex#57]
1) Проститутки стали использовать режим модератора что бы избавиться от особого наказания.
2) Любители писать тем кому они интересны тоже научились так избавляться от капчи.

Они часто бездумно разрешают всё подряд (вероятность корректного решения очень велика).

Предлагаю:
а) не списывать особое наказание за счёт модерирования.
б) не списывать капчи если ранг в минусе.

**Comment by inquisitor6789** [comment]
а) а как тогда кредиты (или капча списывается не при их участии?)? или кредиты доверия отменяются? ведь насколько я знаю, то именно модераторством эти кредиты и зарабатываются
б) а может при понижении рейтинга и кредиты списывать?

У меня встречное предложение - отменить кредиты доверия вообще.

**Comment by mj4444ru** [comment]
я так понимаю это стимуляция пользователей помогать модераторам.
и мне кажется эта система работает и не стоит что то сильно менять.

если убрать списание капчи для тех у кого ранг в минусе, администраторы смогут менять ранг в минус, тем самом временно блокировать возможность списания капч за счёт модерирования.

**Comment by Fenslau** [comment]
Тут не совсем согласен. На начальных уровнях модераторства, много кредитов не заработаешь. А поток жалоб от "клиентов" быстро поставит все на место. Ну да, можно конечно немного подрасти и нарассылать десяток предложений без капчи, но время на это будет затрачено примерно такое же наверно как и на ввод капчей этих всех. Проститутки неизбежны на таких ресурсах. Но они довольно быстро банятся при условии что на них есть жалобы. А иначе их никак наверно не выявить. Я не знаю, есть ли блокировка фото навсегда здесь? Ну то есть например, если анкета заблокирована, то заблокированы будут и все сообщения с таким фото, даже от "новых" пользователей. Это бы помогло, но наверно уже сделано...Проститутка заходит с "новой" анкеты, загружает ту же фотку с расценками на ней, пытается разослать, но даже не подозревает, что ее сообщения уже не доходят никому.

**Comment by mj4444ru** [comment]
так, а у нас уже появилась блокировка фото??? может я чего то не знаю?

на счёт проституток, то смысл скорее не о тех кто будет заблокирован, а о тех кого просто наказываем...

Вот например поступила жалоба на очень грубое сообщения, хочешь разок его наказать, делаешь особое... а оно берёт и списывается за счёт модераторства... и тут понимаешь, что даже не смог наказать... а ведь в большинстве случаев это невозможно заметить...

**Comment by Fenslau** [comment]
Я думаю, что при блокировании юзера, блокируются и все фото, которые были от него навсегда. А значит проститутка, создав новую анкету, уже не сможет такое же фото отправить. Сообщение будет блокированно самой системой и получатель его просто не получит. Она конечно может загрузить новое фото или изменить чутка прошлое и попытаться снова отправить, но так или иначе - просто заибется.

**Comment by mj4444ru** [comment]
А я более чем уверено что разработчики понимают всю глупость данной затеи и никакие фото нигде не блокируются...

**Comment by mj4444ru** [comment]
Кстати что спорить то... Вон знаменитый фак Саши обо всём расскажет...

**Comment by inquisitor6789** [comment]
<. Вон знаменитый фак Саши обо всём расскажет...>
+1
Модерации фото нет

**Comment by Fenslau** [comment]
тогда нет никаких проблем вести хотя бы блокировку фото - из тех анкет, где они уже были заблокированы. Все вото из таких анкет - блокировать на хер. Это тот же первый контур.

**Comment by inquisitor6789** [comment]
Предложите алгоритм. Насколько фото должна быть уникальной (разница в скольких пикселях будет показывать уникальность)? Что делать, если фото своровали у другого пользователя сайта? Тоже блокировать?

**Comment by mj4444ru** [comment]
вот по этому про блокировку фото можно пока забыть...

**Comment by tebaly** [comment]
> так, а у нас уже появилась блокировка фото??? может я чего то не знаю?

Такой фитчи нет (

**Comment by tebaly** [comment]
> Вот например поступила жалоба на очень грубое сообщения, хочешь разок его наказать, делаешь особое... а оно берёт и списывается за счёт модераторства... 

Если тролль - его можно банить. Если чего-то там намодерировал, то оскорбление не самый большой грех - можно бегло просмотреть стату модератора - если есть нарушения - сбросить рейтинг. Если всё норм, закройте глаза на единичные оскорбления, вероятно пользы проекту это Пользователь принесет больше.

Напишите пожалуйста, если таких случаев действительно много, мы попробуем это отрегулировать.

**Comment by tebaly** [comment]
> А я более чем уверено что разработчики понимают всю глупость данной затеи и никакие фото нигде не блокируются...

Впринципе да, как писать против ветра. Но зерно рациональности есть. Мы хотим реализовать идею PR-связей в сообществе, тогда по таким признакам(идентичные фото, сообщения, IP, сигнатура клиента) можно отслеживать мультиакки. Реализация начата, и это будет реализовано. Спасибо.

**Comment by tebaly** [comment]
> Насколько фото должна быть уникальной (разница в скольких пикселях будет показывать уникальность)? 

Сложно, но можно

> Что делать, если фото своровали у другого пользователя сайта? Тоже блокировать?

Вот именно. Такими действиями можно блокировать непричастных пользователей автоматически, в реализации блокировки по изображению.

**Comment by tebaly** [comment]
> вот по этому про блокировку фото можно пока забыть...

Можно сделать. Но вероятнее как элемент PR-связи

**Comment by tebaly** [comment]
Друзья. Товарищ с "факом" - это разработчик спам бота, проверяющий систему на уязвимости. Готовы ли вы гарантировать, что это не кто-то из администраторов? Включите _режим паранойи_ на полную! Возможно это кто-то из нас?!

Способов борьбы со спамерами две:
- Отсутствие возможности к спаму - задача крайне сложна в достижении, не реализована еще никем
- Отсутствие достижения спамерами своих целей, даже при наличии возможности для спама.
- Превышение затрат над полученными результатами.

Все пользователи сайта уведомляются сообщением "Не звоните по телефону и скайпу сразу. Наказывайте мошенников." И дана информация по блокировке запрещенных действий, описаны схемы мошенников. 

Сегодня прикроем лазейку. Давайте поблагодарим лазутчика за его труд, если он таки пробрался в тыл :)

**Comment by inquisitor6789** [comment]
> Друзья. Товарищ с "факом" - это разработчик спам бота, проверяющий систему на уязвимости. Готовы ли вы гарантировать, что это не кто-то из администраторов? Включите режим паранойи на полную! Возможно это кто-то из нас?!

режим паранойи включен и работает на полную :-)
этот перец был еще год назад, когда я только стал админом. Правда тогда у него была одна анкета. Но спустя короткое время после блокировки начали появляться клоны.

**Comment by mj4444ru** [comment]
сформулирую предложение иначе... 
есть пользователи которые бездумно голосуют ради рейтинга... и даже доходили до помощников  админов, я нескольких таких сбросил в далёкой минус... 
но даже в далёком минусе им даются кредиты доверия, что ни есть хорошо...  уберите кредиты доверия у таких людей, а администраторы должны видеть кто чаще ошибается в процентном виде и сбрасывать им рейтинг...  так как 95% сообщений ложные, вероятность ошибки 5% и они этим пользуются, нажимая бездумно "разрешить"...

**Comment by mj4444ru** [comment]
на счёт спам бота :
я конечно не вижу всей картины, но как то не сходится...  для того что он делает, спам бот не нужен, он может сам все это писать... 
по мне так, это человек который любит оскорблять если его отшили и делает это  профессионально...  а вы разработчики давно могли бы сделать сохранение фоток по хешу и завести чёрный список хешей...  фотки в чёрный список добавляли бы администраторы в ручную с учётом всех обстоятельств... если человек отправляет запрещенную фоту, автоматом в бан...

**Comment by tebaly** [comment]
> я конечно не вижу всей картины, но как то не сходится... для того что он делает, спам бот не нужен, он может сам все это писать... 

Вроде с неделю назад стали отправлять фото с расценками от проституток. Проверялась возможность отправки таких фотографий провокацией администраторов.

**Comment by tebaly** [comment]
https://github.com/tebaly/freedomsex/issues/63

>  фотки в чёрный список добавляли бы администраторы в ручную с учётом всех обстоятельств... если человек отправляет запрещенную фоту, автоматом в бан...

**Comment by tebaly** [comment]
> в далёком минусе им даются кредиты доверия, что ни есть хорошо... уберите кредиты доверия у таких людей, а администраторы должны видеть кто чаще ошибается в процентном виде и сбрасывать им рейтинг...

#64

**Comment by tebaly** [comment]
> администраторы должны видеть кто чаще ошибается

#65

**Comment by tebaly** [comment]
> так как 95% сообщений ложные, вероятность ошибки 5% и они этим пользуются, нажимая бездумно "разрешить"...

#66

**Comment by tebaly** [comment]
Прошу прощения если вновь открытые задачи пересекаются с уже обсуждаемыми.

**Comment by tebaly** [comment]
> а) не списывать особое наказание за счёт модерирования.

Пока технически невозможно

**Comment by tebaly** [comment]
> б) не списывать капчи если ранг в минусе.

Если оно не реализовано - сейчас пофиксим.

**Comment by tebaly** [comment]
Реализовано 
`$this->moder->getCredit() > 0 and $this->moder->getRank() >= 0`

Возможны комбинации от значений рейтинга и кредитов.

Далее планируется вводить возможность КУПИТЬ  _кредиты доверия_ 
* решается вопрос с верификацией - спамеры платить не будут, реальным пользователям 1$ не кретичен, если оно того стоит. Если кредиты куплены на реальные деньги, к Пользователю будет повышенное доверие, но без имбы(дисбаланс, диспропорция, как вариант аббревиатура от «I’m Best of All»).
* getRank() ведется для всех пользователей - отсюда возможны конфликт инструментов

**Comment by mj4444ru** [comment]
купить возможность писать всем подрят это то что мне не нравиться у других...

**Comment by tebaly** [comment]
> купить возможность писать всем подрят это то что мне не нравиться у других...

Наказания будут действовать. То есть, кредиты могут быть списаны особым наказанием, как это происходит сейчас. Написал фуфло - заплатил за фуфло. Как-то так. 

На рекламе проект не вытянет. Нужно уходить от этого способа монетизации.

**Comment by mj4444ru** [comment]
введите пожертвования для начала и значек мецината...

**Comment by tebaly** [comment]
Да. Отзывы по данному способу монетизации не впечатляют. 
Попробуем

**Comment by Fenslau** [comment]
Может быть выделить способы монетизации в отдельную ветку? Может быть кто-то что-то предложит. Пара идей есть, но они сырые, но я бы попробовал их развить... Только не за 5 минут. Но возможно какой то вариант мозгового штурма 2-4 могзгов )

**Comment by tebaly** [comment]
#99 франков
