### ISSUE TITLE
Жалобы на сообщения людей из других городов

### ISSUE THREAD

**Issue by mj4444ru** [tebaly/freedomsex#58]
Люди жалуются на сообщения когда им пишут с других городов.
Эти сообщения отклоняются и их подавляющее большинство.
Но как я понимаю в отличии от вирта и неверного возраста, автоматикой тут никто не наказывается.
Может быть сделать пятую категорию сообщений (кроме Разрешено :: Только вирт :: Наказано :: Блокировано): "Город"?
Туда будут автоматически попадать сообщения которые были разрешены, но содержат в себе нарушение. Не справедливо считать их ложными.
Администраторам будет значительно легче видеть злостных нарушителей.

**Comment by inquisitor6789** [comment]
ты удивишься, но если зайти в интерфейс админа и нажать crtl+a то справа от "блокировка" тебя ждет маленький сюрприз :-)

**Comment by mj4444ru** [comment]
ну я чуток о другом. я о разделении группы Разрешено на 2 других (реально ложное и нарушения)...

**Comment by tebaly** [comment]
> тебя ждет маленький сюрприз :-)

Не, это списки городов для блокирования(черный список) с именами та же история

**Comment by tebaly** [comment]
> о разделении группы Разрешено на 2 других

Там с виртом и оскорблении такие бойни устраивают. Вы себе представьте что ещё будет  :flushed:

**Comment by tebaly** [comment]
> Люди жалуются на сообщения когда им пишут с других городов.

Это относится к категории "личное воздействие" 
* не нужно это выносить в администрирование
* такие жалобы "артефакт" от "личного воздействия"
* пользователь получил _по шапке_ за то что пишет не то и не тем
* система захватывает жалобу, так как изначально не известно, на что летит-то
* так как причины для административного наказания нет - якобы безосновательная жалоба
* на самом деле Пользователи междусобойчик устроили и всё порешали таким способом
* бывает, чё. Ссоры и выяснение отношений никто не отменял - но в них не надо лезть))

**Comment by mj4444ru** [comment]
ну эт вы зря... это многих бесит... вот поставил человек галочку хочу только со своего города общаться... а ему пишут только с других городов... по вашему это нормально?
за это же никакого наказания нет...

так вот если пользователь хочет пожаловаться на такого и жмёт удалить, он прав и жалоба адекватная...

> Там с виртом и оскорблении такие бойни устраивают. Вы себе представьте что ещё будет  :flushed:

я говорю что это должна делать автоматика, без ручного вмешательства!

**Comment by mj4444ru** [comment]
опять же это решает вопрос про спамеров которые не попадут в топ по жалобам если не считать ложные жалобы в топе...

**Comment by tebaly** [comment]
> за это же никакого наказания нет...

Есть, по умолчанию. Вы не можете просто так написать человеку из другого города - только через капчу.
