### ISSUE TITLE
Добавить сопроводительный комментарий к жалобе от пользователей

### ISSUE THREAD

**Issue by tebaly** [tebaly/freedomsex#67]
А почему против комментов к жалобе? Я имею ввиду к той, что летит по голосовке? Может это конечно ничего и не даст, коммент тоже можно написать такой, что все подставить в нужном свете... Ну в общем я - за обсуждение )

**Comment by tebaly** [comment]
Да. Спасибо, принято к разработке.

**Comment by tebaly** [comment]
> все и так понятно кто, зачем и почему жалуется... комментарии пишут в замечаниях...
на самом деле фитча крутая. У пользователя будет дополнительная возможность сообщить о нарушении и добавить информативности к жалобе. 

Да, этот коммент нельзя будет показывать "модераторам в голосовалке" - так как может лишь запутать зеленых модеров. Но возможно администраторам дополнительная информация будет полезна. Фитча обсуждается)

**Comment by Fenslau** [comment]
Давайте оценим все плюсы и минусы такого нововведения:
-теряется красота и простота этого действия: так как есть сейчас - нажал и оно полетело.
-тонкие тролли будут писать комментарий, подводящий это сообщение под какую-нибудь вину, но опять таки, регламент же с нами!
-...
+не будет ошибочных жалоб (случайно щелкнул мышкой, или на сенсоре)
+будет понятно, что именно не понравилось в данном сообщении пользователю
+будет меньше намеренных жалоб на все подряд от троллей, когда они поймут, что это уже не имеет смысла
+в сложных случаях поможет лучше разобраться.
+...

**Comment by mj4444ru** [comment]
вопрос в другом...  почему мы должны верить их комментариям? написать все что угодно можно...

**Comment by mj4444ru** [comment]
и сейчас когда удаляешь, открывается окно жалобы...  разве не так? что ещё не хватает?

**Comment by mj4444ru** [comment]
точнее кнопка жалобы становиться красной или типа того...

**Comment by Fenslau** [comment]
Да, хорошее замечание - показывать только админам. 
для mj4444ru - да, это блин недостаток, я согласен, но надо подумать, может быть достоинства перевесят...

**Comment by mj4444ru** [comment]
лучше сделайте кнопку пожаловаться с отправкой всей переписки...

**Comment by mj4444ru** [comment]
а то пришлют 14 и угадай что это такое...

**Comment by tebaly** [comment]
Верно. Нужно мотивировать Пользователей писать именно "Замечания к анкете"
* если вводить фитчу комментария к жалобе, начнется распыление в "показаниях"
* вместо того, чтобы написать "Замечание", пользователь добавит "Коммент" и посчитает это достаточным
* но _ценность_ замечания на порядки выше такого "комментария"

Ввиду озвученного, фитча с комментированием жалоб уменьшит количество замечаний(главный и очень серьезный минус), усложнит обратную связь, затруднит работу администраторам (нужно будет читать еще и эти комменты).

**Comment by tebaly** [comment]
> лучше сделайте кнопку пожаловаться с отправкой всей переписки...

#68

**Comment by Fenslau** [comment]
mj4444ru: и сейчас когда удаляешь, открывается окно жалобы... разве не так? что ещё не хватает?
Да нифига там нету такого, я сам недавно прогнал кое кого по голосовалке и даже не заметил этого )
Комменты можно отображать сереньким в скобках прямо в тексте после жалобы (для админов). 
Замечаниями тоже не все знают как пользоваться. Порой замечание пишут, а сообщениями не подтверждают. Да даже не порой, а часто. А так бы пусть замечания оставались для того чтобы пожаловаться и прокомментить, но чтобы потом в анкете у юзера это висело, а обычные жалобы с комментами - работали бы так же как сейчас.

**Comment by mj4444ru** [comment]
уже так и сделано же...  я писал замечание и прям в обязательном порядке надо было добавить жалобу...  и при нажатии жалобы загорается красным оставить замечание...

**Comment by mj4444ru** [comment]
tebaly, ошибаетесь... жалоба может быть от другого пользователя...

**Comment by tebaly** [comment]
> Да нифига там нету такого

Сейчас появляется фраза "Опубликовать замечание" подсвечивается красным цветом после подачи жалобы

**Comment by tebaly** [comment]
> ошибаетесь... жалоба может быть от другого пользователя...

с этого места поподробнее :) -> #69

**Comment by Fenslau** [comment]
А сама жалоба уже уходит? Вообще, основная мысль была в том, чтобы ограничить пото странных жалоб "ни на что", коих много. Еще недавно пользователь даже мог не заметить, что он кого то обжаловал. Может быть что-то изменилось. Потестить бы, так то мне жаловаться не на кого, а фэйков создавать - еще обвинят в мультиакке ))

**Comment by Fenslau** [comment]
коммент - это ще и защита от троллей, которые не знают, как все происходит, а просто закидывают юзера жалобами. Самое интересное, что одна из них может пройти голосовалку, например потому что действительно была обоснованной и вуаля - пользователь в топ списка активных )

**Comment by tebaly** [comment]
> Потестить бы, так то мне жаловаться не на кого, а фэйков создавать - еще обвинят в мультиакке ))

Это можно. Открывайте вкладку "инкогнито" и вперед :) Ради благого дела же

**Comment by tebaly** [comment]
> например потому что действительно была обоснованной и вуаля - пользователь в топ списка активных )

СеЛяВи :(

**Comment by mj4444ru** [comment]
надо топ считать по принятым, а не всем... и там ещё минусик есть для таких случаев...

**Comment by tebaly** [comment]
> надо топ считать по принятым, а не всем... 

#70

**Comment by Fenslau** [comment]
mj4444ru commented 30 minutes ago
а то пришлют 14 и угадай что это такое...

Ну да, а сейчас типа понятно )) 
вот разберем на реальном примере:
http://sexoo.ru/userinfo/profile/?id=11402013
может быть случай и нетипичный, но вот он, пожалуйста. 
Накидал один необоснованных, а другой подвел ее под топ активных ) Я поставил "минусик", так нет же, кто-то уже после отработанных ею 15 капчах умудрился ее засунуть в плюсик (мож по запарке или еще как). 
А сколько сейчас снимается за необоснованную жалобу?

**Comment by tebaly** [comment]
>  Его замечание прошло, потому что от него была жалоба, но эта жалоба с замечанием никак не связана.

Бывает. Это следствие того, что для пользователей "Упрощены" такие инструменты, поэтому
* Пользователь может отправить жалобу на любое сообщение _в один клик_
* Пользователь может отправить любое по содержанию Замечание.

**Comment by Fenslau** [comment]
Пользователь может отправить жалобу на любое сообщение в один клик
может хотя бы это уберем? Я предлагал через коммент, чтобы еще кое какие положительные цели достичь, но если все таки не примете комменты, то хотя бы в один клик не отправлять?

**Comment by tebaly** [comment]
> вот разберем на реальном примере: http://sexoo.ru/userinfo/profile/?id=11402013

- Так понятно же
- Ложно, ссора, выяснение отношений, отклоненные жалобы

**Comment by Fenslau** [comment]
Да, но я бы не писал, если бы не:
1: с помощью комментов я хотел предложить избавиться от потока жалоб непонятного содержания, как в этом примере
2: почему то эта анкета пользователя вызвала жаркие дискуссии в комментарии к профилю, кто то никак не хотел соглашаться, что нарушение всего одно и капчи за него отработаны.

**Comment by tebaly** [comment]
> хотя бы в один клик не отправлять?

Есть такой принцип при разработке веб интерфейсов
* все пользователи вашего интерфейса глупы и ужасно ленивы.

Отклоненные жалобы мне кажется ничего не усложняют, поправьте
* они просто есть и всё

**Comment by tebaly** [comment]
> кто то никак не хотел соглашаться, что нарушение всего одно и капчи за него отработаны.

Этот кто-то вероятно был неправ

**Comment by tebaly** [comment]
Отклоненные жалобы имеют для системы _ценность_ не меньше чем заблокированные. Попытка уменьшить их число враждебна работающей системе.

**Comment by tebaly** [comment]
На основе "промаркированных" сообщений как "Разрешено", система более доверительно относится к Пользователю. И, как это ни парадоксально
* системе нужно больше жалоб

**Comment by tebaly** [comment]
Жесткая связь "жалоба---замечание" бесспорно уменьшит как количество жалоб, так и количество замечаний, а вместе с ними и количество "адекватных жалоб"

**Comment by Fenslau** [comment]
мм.. Вообще с аргументом, что отклоненные жалобы нужны, я согласен. По крайней мере они точно нужны на данный момент, так как помогают многое понять.
На основании всего этого пока от меня такое предложение: 
1 жалоба + опционально коммент, который писать необязательно. Если коммента нет - по регламенту действуем. Если есть, то принимаем его к вниманию, но действуем по регламенту опять таки. Кто не хочет читать или принимать комменты к вниманию - пусть не читает, я бы читал.
2.
жалоба + замечание (которое будет указано в анкете того, на кого пожаловались) - придумать, как сделать так, чтобы пользователи жаловались на сообщения, которые соответствуют их замечаниям. Я так понимаю, что сейчас механизм работает так. Пользователь что-то понимает и хочет оставить замечание. Щелкает кнопку оставить замечание. Ах, блин, оказывается нужно еще на что то пожаловаться. Может текст поправить? Типа укажите сообщение, которое относится к ЭТОМУ замечанию. этому выделить цветом слегка. 
Ну что еще можно придумать))?

**Comment by tebaly** [comment]
>Пользователь что-то понимает и хочет оставить замечание. Щелкает кнопку оставить замечание. Ах, блин, оказывается нужно еще на что то пожаловаться. Может текст поправить?

Масло масляное. Там только одно замечание, других же нет))

>Нажмите «Наказать и удалить» **у сообщения, которое является причиной замечания**, можно несколько. Это **необходимо, и поможет быстрее определить истину**, а также степень вины.

**Comment by Fenslau** [comment]
Блин, да почему ж тогда они не понимают то.. Короче надо потесть. Попробую сейчас пару анкет создать, может что то прояснится....

**Comment by mj4444ru** [comment]
нельзя делать комментарии к жалобам... их будут использовать ТОЛЬКО для ИСКАЖЕНИЯ смысла...

**Comment by mj4444ru** [comment]
нельзя уменьшать количество жалоб...

**Comment by tebaly** [comment]
Благодарю за участие в обсуждении предложения. Итог:
* нельзя делать комментарии к жалобам... их будут использовать ТОЛЬКО для ИСКАЖЕНИЯ смысла...
* нельзя уменьшать количество жалоб...
* и я того же мнени я

На этом давайте пока прикроем эту проблему)

**Comment by Fenslau** [comment]
Тааакк... Более менее понятно но пока частично. Буду писать в одном сообщении, но много, что удалось натестить: прошу прочитать все с начала до конца, когда будет конец, скажу !всё.
Иначе я просто всё не запомню... Итак:
1. Опубликовать замечания: тут все норм, но хотелось бы чтобы был акцент именно на всех жалобах, связанными, с этим замечанием, !!!!В том числе и фото!!!, если оно связано с сообщением, причем чтобы пользователь понимал, что нужно это все маркировать одним действием, иначе потом пользователь улетает в удаленные, переписку с ним они найти "не могут" некоторые. 
Даже если потом пользователь найдет этот контакт и захочет еще раз его наказать или опубликовать новое замечание, так как старое отклонили за недостаточностью сведений - нужно чтобы замечание не принималось автоматически, как говорил 4444 (это баг?), и чтобы не удалялась вся переписка при переносе пользователя из заблокированных в разблокированные, а то не на что будет жаловаться.
2. По клику удалить и наказать: да, высвечивается красненьким "опубликовать замечание", это уже хорошо. Но, все летит на голосовку в один клик - все помним про случайные клики мышки и сенсорные устройства. Повторюсь, даже я, юзая ноут, прогнал по голосовке мою собеседницу, хотя даже не заметил, как это произошло.
3. Если мы нажимаем "удалить и наказать", то пользователь уже будет в "удаленных" Однако если мы туда зайдем и нажмем на его анкету, то в ней будет опять предложение заблокировать. Вместо разблокировать. Если же мы хотим его разблокировать все же, то нужно его еще раз в удаленных "заблокировать", а потом уже разблокировать, тогда он снова появится в контактах....
пока !все

**Comment by mj4444ru** [comment]
1. я так понимаю удалённые это не блокировка, а просто статус который не ограничивает общение... я прав?

2. чтобы повторно написать замечание, жаловаться второй раз не нужно, замечание уже есть...

3. у меня с телефона только по второму клику срабатывает (не знаю почему так)... может для мобильных устройств так задумано? так то удобно получается от случайных кликов, только надо сообщить что надо второй раз ткнуть...

**Comment by tebaly** [comment]
Reopen issue - заново открывает тикет.

Но вы уже начали новый, так даже лучше

**Comment by tebaly** [comment]
> у меня с телефона только по второму клику срабатывает (не знаю почему так)...  может для мобильных устройств так задумано? 

Пожалуйста, откройте новый тикет, и опишите проблему подробнее - возможно баг
Спасибо
