### ISSUE TITLE
Жалоба может быть от другого пользователя...

### ISSUE THREAD

**Issue by tebaly** [tebaly/freedomsex#69]
Жалоба может быть от другого пользователя

**Comment by mj4444ru** [comment]
когда оставляешь замечание, наличие жалоб проверяется от всех пользователей...  если хоть одна есть, можно не жаловаться...

**Comment by tebaly** [comment]
А, это да :)

**Comment by tebaly** [comment]
Стоит исправить?

**Comment by mj4444ru** [comment]
да... 
есть и обратный глюк... собеседник первым сообщением прислал фото...  жмешь удалить...  если других жалоб нет, замечание оставить не возможно...

**Comment by tebaly** [comment]
Там был смысл
* Ограничить возможность подачи Замечания, когда жалоб нет совсем
* Кто-то мог пожаловаться, но поленился отправить замечание
* Затем, кто-то отправляет замечание, но от него уже не требуют жалобы, так как жалоба уже была кем-то отправлена ранее

Вы считаете, что алгоритм нужно править?

**Comment by tebaly** [comment]
> есть и обратный глюк... собеседник первым сообщением прислал фото... жмешь удалить... если других жалоб нет, замечание оставить не возможно...
#71

**Comment by mj4444ru** [comment]
да, хочешь пожаловаться, будь добр прикрепи основание...
или поставь галочку "я согласен на передачу переписки администраторам ресурса"...

**Comment by tebaly** [comment]
И всё же хотелось иметь максимальный охват "замечаний"
* чтобы пользователь мог легко оставить замечание
* если он первый кто пишет замечание - обязать направить жалобу
* для упрощения, если жалобу ранее кто-то отправлял, не требовать

Может в рекомендательной форме?
* подкрепите ваше замечание доказательством, нажмите "наказать и удалить" ... ...

**Comment by mj4444ru** [comment]
> для упрощения, если жалобу ранее кто-то отправлял, не требовать

для упрощения есть кнопка пожаловаться/удалить...

ну как вы себе представляете: подаёте на человека в суд, а доказательств нет...
бред, я такие замечания никогда не пропускаю...

в редких случаях замечание дополняет жалобу другого пользователя... но в на столько редких, что это можно не учитывать...

**Comment by tebaly** [comment]
> ну как вы себе представляете: подаёте на человека в суд, а доказательств нет...

Рассмотрение дела переносится до появления доказательств)
* здесь также, жалоба может последовать от другого пользователя позже
* а замечание уже имеется, но было вами отклонено
* при новых обстоятельствах, замечание можно будет опубликовать

У имеющегося но отклоненного замечания есть плюс, по сравнению с его полным отсутствием.

Давайте не будем столь категоричны, и попробуем просить "дополнительно" кликнуть по сообщениям при подаче Замечания - в добровольной форме
