### ISSUE TITLE
Глюк... первым сообщением фото...  замечание оставить не возможно...

### ISSUE THREAD

**Issue by tebaly** [tebaly/freedomsex#71]
есть и обратный глюк... собеседник первым сообщением прислал фото... жмешь удалить... если других жалоб нет, замечание оставить не возможно...

**Comment by Fenslau** [comment]
А вы мою ветку прикрыли? Я просто там большой комментарий написал с результатами теста ))) чуть было весь текст не пропал. Куда его теперь написать то?

**Comment by Fenslau** [comment]
Дело в том, что при повторном замечании того же пользователя на того же, замечание публикуется без предложений навыбирать еще новых сообщений для прува. А иногда именно это и нужно! Но в моем комменте есть и еще много чего. + я бы хотел оставить дополнение, которое, возможно выльется в новую ветку

**Comment by tebaly** [comment]
> А вы мою ветку прикрыли? 

Вроде нет, открыто же #74

кнопка "Reopen" открывает обсуждение снова :wink:

**Comment by mj4444ru** [comment]
http://freedomsex.net/userinfo/profile/?id=11182248
человек смог написать замечание при только жалобах на фото

или глюк устранили, либо проблема была несколько другая

**Comment by tebaly** [comment]
> человек смог написать замечание при только жалобах на фото

Значит проблема отсутствует..
