### ISSUE TITLE
Некорректна ссылка на администратора ... замечание

### ISSUE THREAD

**Issue by tebaly** [tebaly/freedomsex#72]
иногда случается, что некорректна ссылка на администратора опубликовавшего/отклонившего замечание

**Comment by tebaly** [comment]
Нужны подробности

**Comment by inquisitor6789** [comment]
http://freedomsex.net/userinfo/profile/?id=5701697
>обзывается. ай ай ай как не красиво!
#5929276 - Отклонить - Принято - @5040613 - 25 минут назад

стопудово я его не публиковал

**Comment by tebaly** [comment]
>  Принято - @5040613 - 25 минут назад
> стопудово я его не публиковал

Вы. Просто это было не 25 минут, а год назад #73

**Comment by inquisitor6789** [comment]
ок. если год назад, то возможно и я. Память не настолько хорошая :-)
но вернемся в нашим баранам - не проще ли сделать дату не сколько-то времени назад, а просто дата события? Думаю, что вопросов тогда будет меньше

**Comment by tebaly** [comment]
Сейчас там `true` данные - 12 месяцев назад :)
