### ISSUE TITLE
Некорректные даты в замечаниях.

### ISSUE THREAD

**Issue by tebaly** [tebaly/freedomsex#73]
Накидайте пожалуйста подробностей. Я попробую разобраться

* Некорректные даты в замечаниях - это дата обновления скорее всего

**Comment by mj4444ru** [comment]
нет, я много раз видел, типа я 15-30 минут назад одобрил или отклонил замечание... но я то знаю что это было несколько дней назад... а если бы кто то другой обновил, там уже был ба не я...
и не надо вариантов что с моего аккаунта кто то другой сидит, это не только я замечал...

**Comment by tebaly** [comment]
Читаем внематочно
1.3. В случае, если собеседник и Пользователь находятся в разных странах, законодательство одной страны перекрывает законодательство другой с приоритетом запрещенных действий.

То есть - банить обоих :) ну или того, кто из РФ

**Comment by tebaly** [comment]
Отображается _дата обновления_ 
* обновляется при смене решения
* обновляется при _одобрении_ Пользователями - лайк  (причина)

Можно
* добавить третью графу даты _изменено решение_

**Comment by mj4444ru** [comment]
да, разделите, пусть будет 3 даты...
написано, изменено, лайкнуто

**Comment by tebaly** [comment]
Ещё немного деталей))
* даты добавления оказывается фактически нет
* датой добавления принято считать время последнего решения

Т.о. третья графа не нужна. Сейчас пофиксим

**Comment by tebaly** [comment]
Исправлено. Благодарю за помощь

**Comment by mj4444ru** [comment]
ну и я о том же, дата обновления это дата последнего решения... 
а как же дата жалобы и дата лейка?

**Comment by tebaly** [comment]
А они в сущности нужны?
* сейчас видно когда последний раз принималось решение

Автоматика учитывает 
* время обновления лайков

Нужна ли дополнительная информация?

**Comment by tebaly** [comment]
Закиньте как новую проблему пожалуйста.
