### ISSUE TITLE
результаты теста на "наказать и удалить" и на "оставить замечание"

### ISSUE THREAD

**Issue by Fenslau** [tebaly/freedomsex#74]
Тааакк... Более менее понятно но пока частично. Буду писать в одном сообщении, но много, что удалось натестить: прошу прочитать все с начала до конца, когда будет конец, скажу !всё.
Иначе я просто всё не запомню... Итак:
1. Опубликовать замечания: тут все норм, но хотелось бы чтобы был акцент именно на всех жалобах, связанными, с этим замечанием, !!!!В том числе и фото!!!, если оно связано с сообщением, причем чтобы пользователь понимал, что нужно это все маркировать одним действием, иначе потом пользователь улетает в удаленные, переписку с ним они найти "не могут" некоторые. 
Даже если потом пользователь найдет этот контакт и захочет еще раз его наказать или опубликовать новое замечание, так как старое отклонили за недостаточностью сведений - нужно чтобы замечание не принималось автоматически, как говорил 4444 (это баг?), и чтобы не удалялась вся переписка при переносе пользователя из заблокированных в разблокированные, а то не на что будет жаловаться.
2. По клику удалить и наказать: да, высвечивается красненьким "опубликовать замечание", это уже хорошо. Но, все летит на голосовку в один клик - все помним про случайные клики мышки и сенсорные устройства. Повторюсь, даже я, юзая ноут, прогнал по голосовке мою собеседницу, хотя даже не заметил, как это произошло.
3. Если мы нажимаем "удалить и наказать", то пользователь уже будет в "удаленных" Однако если мы туда зайдем и нажмем на его анкету, то в ней будет опять предложение заблокировать. Вместо разблокировать. Если же мы хотим его разблокировать все же, то нужно его еще раз в удаленных "заблокировать", а потом уже разблокировать, тогда он снова появится в контактах....
пока !все

**Comment by Fenslau** [comment]
Например, можно вывешивать баннерок, или как его там, после "наказать и удалить", что возможно вы пожаловались не на все сообщения, если хотите найти этого пользователя в контактах, то он теперь в "Удаленных". Ну короче интерфейс по наказанию нужно доработать, но с сохранением минимализма, как сейчас.

**Comment by tebaly** [comment]
> но с сохранением минимализма

В этой части не _минимализм_, а вынужденная упрощенность. 
* чтобы у пользователя оставалось желание жаловаться и "Замечать"
* если мы ему уведомлений накидаем - это раздражает же, чем меньше чего-то выскакиивает, тем Пользователю спокойнее
* там как раз-таки написано  "можно несколько"

Вам не кажется, что если сделать _ акцент именно на всех жалобах_ 
* таки они и накликают на всех
* а что, лишним же не будет

Мы _аккуратно_ попросили Пользователей кликать на _целевой_ жалобе, и возможно не одной. Чтобы не провоцировать их кликать на всё подряд - они могут, поверьте

**Comment by Fenslau** [comment]
Просто такое ощущение, что у пользователя сейчас просто огромное желание жаловаться и замечать ) 
Хотя некоторые наоборот, до сих пор пренебрегают этим способом. То ли не верят, что это поможет, то ли воспитаны просто так, что не привыкли ябедничать.... 
Тем, кто жалуется, возможно не хватает обратной связи какой-то для лучшего понимания. Они же не знают, наказан в результате их оппонент или нет. 
А такой еще момент. За необоснованную жалобу сколько капч сейчас? То есть если пользователь скинет всю переписку, он может ведь наверно в глубокой капче застрять?)

**Comment by tebaly** [comment]
> То есть если пользователь скинет всю переписку

Там несколько лимитов - даже при максимуме не смертельно.

**Comment by tebaly** [comment]
На данный момент решено не связывать жестко эти две сущности 
#94
