### ISSUE TITLE
некоторые сообщения маркируются серым. что это?

### ISSUE THREAD

**Issue by inquisitor6789** [tebaly/freedomsex#75]
собственно вопрос в сабже
http://freedomsex.net/userinfo/profile/11769180

@10427814 - История - Арбитраж - 2 дня назад
Пососешь за деньги

**Comment by Fenslau** [comment]
Хм, а я думал, что только у меня такой вопрос...

**Comment by tebaly** [comment]
Не попали на голосование в виду
* массовой подачи необоснованных жалоб Пользователем
* можно кстати подкрутить, и серенького станет больше
* надо ли?

**Comment by inquisitor6789** [comment]
qsdfgsdfgsdfv

**Comment by tebaly** [comment]
Таки соберитесь и решите
* нужно больше необоснованных жалоб, или меньше?

:neckbeard:

**Comment by inquisitor6789** [comment]
а что в "Пососешь за деньги" необоснованного?

**Comment by tebaly** [comment]
В ней нет, но на ней мир жалоб не заканчивается) 

Не попали на голосование в виду **массовой подачи** необоснованных жалоб Пользователем
* здесь _необоснованность_ предполагается.
* в этом случае обоснованна, в иных нет

http://freedomsex.net/userinfo/profile/?id=8436916
* А почему тебе парни не интересуют!?
* Хоть бы ответила
* А тебя правдо анюта завут

**Comment by tebaly** [comment]
Надеюсь в полезности "лишних" жалоб мне удалось всех убедить. Но вот нужно ли их количество делать ещё больше?
* Вопрос

**Comment by inquisitor6789** [comment]
убедить удалось, но не совсем. Насколько я понял алгоритм, то при вынесении вердикта на жалобу "привет" он (вердикт) заносится в базу и в дальнейшем вердикты по таким жалобам принимаются автоматически. Весь вопрос только во времени наполнения базы.

Возвращаясь к нашим баранам, что мы имеем - какой-то ничтожный процент жалоб не попадает на голосование только лишь из-за того, что на этого пользователя идет большой поток "необоснованных" жалоб. Причем алгоритм этот мне совсем не понятен.

Если рассматривать профиль http://freedomsex.net/userinfo/profile/11769180 
то мне совсем не понятно по какой причине "пососешь за деньги" попало в пропущенные а по всем остальным жалобам в это же самое время выносился вердикт. По логике они тоже должны были попасть в пропущенные. Или берется какой-то совсем узкий временной интервал?

**Comment by tebaly** [comment]
> Весь вопрос только во времени наполнения базы.

Какой именно?)

> что на этого пользователя идет большой поток "необоснованных" жалоб. 

Не на, а от. Когда кто-то без разбору начинает штамповать жалобы, срабатывает фильтр

>  по какой причине "пососешь за деньги" попало в пропущенные а по всем остальным жалобам в это же самое время выносился вердикт.

Случайность и совпадение

> Или берется какой-то совсем узкий временной интервал?

Количество за время

---
На данный момент, команда Администраторов друг другу противоречит
* кто-то против _потока жалоб_, и предлагает способы его уменьшить 
* вы предлагаете ослабить _лимит на количество_ жалоб от одного пользователя за период времени
* поток жалоб увеличится

**Comment by tebaly** [comment]
Ради эксперимента, такого рода лимит можно отключить вовсе
* нормальное количество жалоб увеличится
* раздолье для DDOS по системе администрирования
* отсутствие _лимита_ подразумевает возможность автоматической генерации бреда
* поток бреда парализует интерфейс

**Comment by tebaly** [comment]
Переоткройте пожалуйста задачу, если необходимо

**Comment by Fenslau** [comment]
Тут надо кстати подумать. Фильтр многочисленных жалоб от пользователя - штука хорошая. И нужная. Без нее точно никак. Какой коэффициент или зависимость - другой вопрос, но наверно как было всегда - и норм. А кстати, какие настройки? Сколько пользователь должен отправить жалоб в (час?), чтобы (какой % из них) стал пролетать мимо голосовки? 
Но я предлагаю сделать в интерфейсе возможность отправить на арбитраж случайно пропущенную жалобу, если вдруг все таки она будет увидена админом.

**Comment by tebaly** [comment]
> предлагаю сделать в интерфейсе возможность отправить на арбитраж случайно пропущенную жалобу, если вдруг все таки она будет увидена админом.

#95

**Comment by Fenslau** [comment]
http://sexoo.ru/userinfo/profile/5943901/
Целый месяц никто не видел его предложения встретиться за деньги. Обратите внимание, на сколько велико совпадение. 7 жалоб месяц назад. Даже если они были все в один день! Какова вероятность того, что в серое попали именно эти. Ничтожная! Что то не то в алгоритме, или я туплю??

**Comment by Fenslau** [comment]
Может быть проверить алгоритм... бред конечно, но действительно ли жалобы улетают в серое только при большом количестве жалоб от пользователя? А то мож потом все идентичные туда же летят, но уже без условий а? не может такого быть?

**Comment by tebaly** [comment]
`низкий рейтинг модератора: -29`
* в таких случаях тоже, или только в таких, жалоба не входит на голосование

Сейчас сделаем возможность арбитражить _серое_

**Comment by tebaly** [comment]
> не может такого быть?

Мы можем многое)

**Comment by tebaly** [comment]
Теперь можно арбитражить _серое_

**Comment by tebaly** [comment]
Для серого отдельный котел #97

**Comment by Fenslau** [comment]
Появилась идея. Сыроватая, но: 
От девушек жалоб ясное дело больше. Их достают спамеры вирта, фотостручки и прочее. Если девушка онлайн и ее бесит, что ей все написывают с предложениями (а это так и есть). Она может в конце концов наиболее навязчивые отправить в наказать и удалить, просто чтобы избавиться уже от этой навязчивости. Ну конечно если она не проститутка. Получается, что и серого от нее будет больше. Причем Может это сделать просто - справа всплывают же окошки - мол непрочитанные сообщения. Она их читать не хочет. И уже закрывала ни раз! А они все равно появляются. Она злится и просто уже нажимает наказать, чтобы они больше не появлялись, она не хочет эту тонну разгребать. _Реально_ бывает так, что одной и той же девушке написывает один и тот же юзер, не смотря на то что она его сообщения не читает, он пишет что с ней хочет сделать и т.п. У нее не хватает времени найти его в сообщениях и заблокировать, или она еще не разобралась, как это сделать, потому что только что пришла. 
Мы должны бороться за большее количество онлайн девушек на сайте (реальных). От этого зависит развитие сайта. Поэтому предлагаю:
(мы при этом не нарушим никакие права, а наоборот защитим):
+сделать для девушек возможность побыть вне сообщений какое то время - на видном месте, там же справа вверху, разместить опцию "не писать мне в течение хх минут" при этом сообщения просто будут игнориться.
+сделать возможность отметить все сообщения как прочитанные, без блокировки анкет, если захочет, потом вернется к ним, лишь бы они не мелькали и не пикали. 
+если она закрыла всплывающее сообщение справа вверху, то больше от этого контакта сообщения всплывать не будут, пока она их не прочитает.
+добавить для нее опцию по желанию: "отобразить сообщения только по моему профилю, остальные удалить/пометить как прочитанные, проигнорированные/...()
Все это отображать при количестве сообщений новых, превышающих хх и отображать сверху от первого всплывающего сообщения.

**Comment by tebaly** [comment]
Всё хорошо. По формату Git 
* посчитайте количество предложенных идей для обсуждения
* в формате Git - одна идея = одна Issue(проблема)

Была проблема 
> некоторые сообщения маркируются серым. что это?

Она решена. Зачем сюда писать?)

У нас есть негласная задача, глобально
* **сделать так, чтобы девушки отвечали на сообщения**
* мы не рассматриваем варианты инструментов позволяющие _игнорировать_

### Для продолжения обсуждения, пожалуйста, откройте новый тикет
