### ISSUE TITLE
Спорные ситуации

### ISSUE THREAD

**Issue by mj4444ru** [tebaly/freedomsex#78]
http://freedomsex.net/history/message/97309481/
Я не о тексте, а о ситуации...

Я специально отправил решение в арбитраж и не стал выносить решение что бы кто то третий вынес решение, так сказать рассудил...
Но получается что тот же человек повторно выносит решения, тем самым создавая спор...
Если разработчикам не хочется что то писать на серверной стороне, то хотя бы в давайте в регламенте запретим повторно принимать решения...

Хочу услышать ваши мнения...

**Comment by tebaly** [comment]
Да можно запретить. Смотрите
* вы сбросили это решение, а он снова его вынес
* а вы не можете повторно сбросить (вы это тоже раньше предлагали)

* вы приняли решение, а через некоторое время встретили его в арбитраже
* вы не можете вынести решение, вы его уже выносили

_Палка о двух концах_

**Comment by tebaly** [comment]
> Но получается что тот же человек повторно выносит решения, тем самым создавая спор...

Ловля на живца - сбросьте ему рейтинг, если ошибка явная, или игнорируются ваши комментарии и возражения. Попробуйте выяснить, почему он так настойчиво допускает ошибку.

> Хочу услышать ваши мнения...
Мы не хотим вводить в интерфейсе _жестких ограничений_ - их сейчас практически нет. 
* в этом сила, если присмотреться

**Comment by tebaly** [comment]
И я повторюсь - вы предлагаете изменять систему, при этом 
* берете во внимание сложные случаи - они приравниваются к ИСКЛЮЧИТЕЛЬНЫМ ситуациям
* то бишь, исключение из правил - сложно, или невозможно нормировать

Перестаньте меня троллить :tired_face: :sob: :sob: :sob:
