### ISSUE TITLE
Понижение рейтинга админа только после согласия не менее 2 админов других админов.

### ISSUE THREAD

**Issue by mj4444ru** [tebaly/freedomsex#80]
Предлагаю добавить в регламент:
Если мы хотим по какой либо причине понизить рейтинг админа, мы должны заручится поддержкой двух других админов и указать их айди в причинах понижения рейтинга.

И чисто по совести, этого вообще нельзя делать в отношении других админов при любых обстоятельствах, даже если ты совсем совсем не согласен с какими то решениями... Исключение лишь явные признаки взлома аккаунта админа...

**Comment by inquisitor6789** [comment]
> должны заручится поддержкой двух других админов
как это предлагается осуществить? В личке? Оперативность ответов не гарантирована. А бывает, что надо быстро вредителя остановить.

**Comment by mj4444ru** [comment]
что значит вредитель?
как его вычислить?
и что он может сделать?
и какой такой непоправимый вред он может нанести?

**Comment by inquisitor6789** [comment]
> что значит вредитель?

например админ, принимающий заведомо не верные решения, публикующий необоснованные жалобы

> как его вычислить?

когда раздел арбитража переполняется :-)

> и что он может сделать?
и какой такой непоправимый вред он может нанести?

такого чтобы нельзя было исправить ничего. Но это время. И жалобы пользователей

**Comment by inquisitor6789** [comment]
а какова цель введения такого голосования?

**Comment by mj4444ru** [comment]
это не голосование, это заручится поддержкой... думаю такое соглашение исключит использование понижения рейтинга в любых конфликтных ситуациях... а в случае экстренной ситуации будет возможность нейтрализовать вредителя...

**Comment by mj4444ru** [comment]
Если человек массово что то делает, что становится крайне трудно исправить, думаю ни один администратор не осудит другого администратора за понижение рейтинга.

Если таких действий произошло 50 в течении часа и это продолжается, то действительно можно применить особое... во всех остальных случаях можно подождать...

Опять же, соглашение касается только людей ранга администратор. Всех остальных можно понижать в случае если администратор считает его действия подозрительными.

**Comment by tebaly** [comment]
> в случае экстренной ситуации будет возможность нейтрализовать вредителя

а мы иначе сделаем) резиденты смогут _доначислить_ рейтинг кому угодно, если посчитают нужным. Поэтому
* если сброс не оправдан, рейтинг может быть восстановлен любым резидентом
* администратор - это высокий уровень доверия. Если сбросил, значит причина есть, и он в состоянии ее аргументировать
