### ISSUE TITLE
Стоит ли наказывать за предложения вирта тем кому он не интересен

### ISSUE THREAD

**Issue by mj4444ru** [tebaly/freedomsex#81]
Предлагаю наказывать за предложения вирта тем кому он не интересен
как вариант в виде капчи (до 10 капч за каждую жалобу на вирт).

**Comment by tebaly** [comment]
Каким образом? 
* не все Пользователи, которым интересен вирт указывают это в анкете

**Comment by mj4444ru** [comment]
что значит как ? капчами... 

сейчас и так капча начисляется...  пусть в случае с жалобой ещё несколько раз введут...

**Comment by tebaly** [comment]
За любую "личную" жалобу дается капча

Давайте конкретизируем задачу - очередность
* поступила жалоба 
* произведена оценка "вирт"
* повторно поступает жалоба идентичного содержания
* мултипликатор наказания +10

Всё верно? Дополните если нужно

**Comment by mj4444ru** [comment]
так можно, но это слишком частный случай...

**Comment by tebaly** [comment]
Если слишком частный, то зачем реализовывать? Если не частный, предложите пожалуйста решение более конкретно. Я запутался уже
