### ISSUE TITLE
Голосование на замечания на самого себя

### ISSUE THREAD

**Issue by mj4444ru** [tebaly/freedomsex#83]
http://freedomsex.net/history/message/97678113/

Можно голосовать за замечания отправленные на самого себя...
Это баг или фича?

Сразу узнаешь что человек на тебя пожаловался...
Ну и можно на рейтинг голосования влиять в спорных ситуациях...

**Comment by tebaly** [comment]
Голосовать можно за отправленное собственноручно. Если отправили на вас - вы этого не узнаете.

**Comment by mj4444ru** [comment]
всё с точностью наоборот... за отправленное собственному но голосовать нельзя, так как сама жалоба уже голос. 

если отправили на вас, вы можете проголосовать и вы это узнаете...  и ещё оно будет удалено, по этому тоже узнаете...

**Comment by mj4444ru** [comment]
это сейчас так у вас...

**Comment by tebaly** [comment]
Поправили. Понаблюдайте пожалуйста. 
Теперь ни то ни другое показываться в голосовании не должно
