### ISSUE TITLE
Причина блокировки анкет

### ISSUE THREAD

**Issue by mj4444ru** [tebaly/freedomsex#84]
http://freedomsex.net/userinfo/profile/?id=3296093
Человек спрашивает почему его анкета заблокирована...
Как вообще понять почему? 
Хорошо бы знать причину, что бы понимать стоит ему вообще отвечать и порекомендовать завести новую анкету или лучше не общаться с ним.

**Comment by tebaly** [comment]
Кто-то из вас отметил жалобу из двух слов "платный вирт" как заблокировать. Система не различает знаков пунктуации, не видит смайлов и символов(видит особым образом)
* этот пользователь отправил сообщение "платный вирт?" 
* его анкеты была автоматически заблокирована

1. "Блокировать" нужно _ёмкие_ по содержанию сообщения, когда всё очевидно.
2. Интересоваться, запрашивать и обсуждать ОПЛАТУ интим услуг _запрещено_

**Comment by tebaly** [comment]
На этапе администрирования была допущена ошибка - заблокированный текст не является очевидным либо однозначным - с любыми знаками препинания нет ясности
* платный вирт - сравните с "у меня платный вирт"
* платный вирт? - хочет ли человек оплатить услугу или интересуется с другими целями?
* платный вирт! - человек возмущен чем-то??..

Пользователь отправил сообщение содержанием похожим на запрещенное
* а мы делать так крайне не рекомендуем, так как - получите и распишитесь
* может глюкнуть автоматика - а она тут сделала всё по правилам
* может глюкнуть Администратор, и "перегнуть палку" в тех случаях, когда это не нужно

Кто виноват?

**Comment by mj4444ru** [comment]
я вобщем то о другом.... указывайте причину блокировки...

**Comment by mj4444ru** [comment]
открытые проекты значительно надёжнее защищены чем закрытые...
хотя закрытые сложнее сломать...
но в конечном итоге открытость даёт большую степень защиты...
хотя многие тонкости всё же нельзя открывать, должны быть свои секреты...

**Comment by tebaly** [comment]
Давайте в этом вопросе остановимся на том, что это сугубо техническая информация
* необходимая только разработчикам с целью отладки работы системы

Обработка такой информации - в ручном режиме, по запросу, на усмотрение разработчиков
