### ISSUE TITLE
Может добавим ссылок в нужные места

### ISSUE THREAD

**Issue by Fenslau** [tebaly/freedomsex#88]
Чтобы копипэйстом не заниматься! Например в профиле чтобы можно было кликнуть на того, от кого жалоба поступила и посмотреть, кто там. Иногда полезно бывает. Чтобы понять, кому там вирт наспамили.

**Comment by inquisitor6789** [comment]
+1

**Comment by tebaly** [comment]
> чтобы можно было кликнуть на того, от кого жалоба поступила и посмотреть, кто там

Это информация с ограниченным доступом - только Администраторам, расположена в профиле Нарушителя. 
* в списках данной информации нет, так как для них установлен уровень доступа ниже
* жалобы планировалось делать анонимными вовсе

**Comment by inquisitor6789** [comment]
> @8989074 - тот кто отправил жалобу

при клике открывается 
http://freedomsex.net/argue/profile/8989074
а хотелось бы чтобы открывалось http://freedomsex.net/userinfo/profile/?id=8989074
админский профиль в данном случае бесполезен

**Comment by tebaly** [comment]
Была следующая идея
* все участники Сообщества являются модераторами так или иначе
* модератор по умолчанию - если пользователь нажимает "наказать и удалить" или оставляет Замечание к анкете - пассивный модератор
* активный модератор - принял условия администрирования, имеет доступ в админку

Таким образом, идеологически, отправивший замечание является Модератором, даже если не принял соглашения администрирования и не участвует в нем. 
* ссылка на профиль модератора дает возможность просмотреть его активность

Вариант:

От @8989074 - Профиль - История - Арбитраж - Принято @11768245 - 8 дней назад

**Comment by inquisitor6789** [comment]
ок. с моей стороны возражений нет

**Comment by mj4444ru** [comment]
про идеи всё и так понятно

в истории по жалобе (http://freedomsex.net/history/message/*/) тоже добавьте ссылку на профиль в каждом голосе

**Comment by tebaly** [comment]
Готово

Пожалуйста, открывайте новую задачу по новой проблеме. 
#91
Спасибо.

**Comment by Fenslau** [comment]
16:13  #12525689 - Профиль - Арбитраж - История
Блядина давай я тебе буду скидывать фотки с бывшей, а ты ее будешь жёстко унижать и оскорблять матом!
Непонятно, кто пожаловался на это сообщение в сером. Для вердиктов было б полезно знать, давайте добавим.

**Comment by tebaly** [comment]
@Fenslau - пожалуйста, если есть новая проблема, добавьте ее как новую Issue
* ветка называется "Может добавим ссылок в нужные места"
* а проблема в том, что не отображается ссылка на "кто пожаловался"
* согласитесь, это баг, достойный отдельной ветки :)

**Comment by tebaly** [comment]
#133
