### ISSUE TITLE
Есть идея - добавить некоторую инфу о пользователе для админов

### ISSUE THREAD

**Issue by Fenslau** [tebaly/freedomsex#89]
Идея не нова, была реализована на другом проекте. Помогала вычислять спамщиков, выделять из них нормальных и т.п.
Короче в профиле пользователя предлагаю отображать следующую инфу:
Общее количество сообщений.
Количество сообщений, оставшихся без ответа.
Количество сообщений в час (среднее), естественно учитываются те, пока пользователь был онлайн. 
Так...что еще. 
Предлагайте - еще какое-то количество сообщений по отношению к чему-либо. Это может быть полезно. Сначала может показаться, что это мало что даст, но на самом деле - это очень полезная инфа!
По началу мы можем немного подзапутываться, так как я не могу сказать, какие показатели "нормальны" именно для этого ресурса, а какие подозрительно. Но это вскоре станет понятно и по этой статистике мы сможем много о чем судить. И даже сделать в будущем индикаторы, сразу типа цветом подсвечивать эти количества для упрощения понимания, когда наберем статистику и решим что норма, а что - какое либо отклонение

**Comment by mj4444ru** [comment]
Это всё невозможно... Если кто то надумает написать робота, он предварительно изучит админку и  максимально скроет своего робота так что вы точно никогда его не вычислите...

Я только вот одного не понимаю... У нас разве есть проблемы со спамом?
Тех кто пишет всем подряд и сейчас прекрасно видно...

**Comment by tebaly** [comment]
> По началу мы можем немного подзапутываться, так как я не могу сказать, какие показатели "нормальны" именно для этого ресурса, а какие подозрительно. 

У нас нет и не будет доступа к переписке Пользователей. Гадать на цифрах?
* мы немного перешагнули такой подход - у нас есть жалобы и замечания
* у нас есть автоматика - которая контролирует некоторые "соотношения" чисел

Со спамом проблемы пока действительно нет - у нас это весьма сложное занятие :grin:

**Comment by tebaly** [comment]
> Общее количество сообщений.
Количество сообщений, оставшихся без ответа.
Количество сообщений в час (среднее), естественно учитываются те, пока пользователь был онлайн. 

Эта информация отдана на анализ автоматике
Спасибо за новые идеи. В обсуждениях рождается истина
