### ISSUE TITLE
Замечания скрываются в общедоступной части через пол года

### ISSUE THREAD

**Issue by mj4444ru** [tebaly/freedomsex#90]
Замечания скрываются в общедоступной части через пол года
У замечания есть кнопочка согласен с замечанием (лайк), предлагаю что бы она обновляла дату скрытия замечания

Например:
- Модератор одобрил замечание, время до скрытия установилось 6 месяцев.
- Прошёл месяц, время до скрытия 5 месяцев.
- Кто то лайкает замечание, время до скрытия установилось снова 6 месяцев.

**Comment by tebaly** [comment]
Приблизительно так и должно было быть. Проверю

**Comment by tebaly** [comment]
Ошибки нет.
* жалобы в принципе не удаляются - есть все от 2014 года
* выбираются все, вне зависимости от даты
* сортировка по дате _обновления_ и _лайкам_
* есть лимит 10 одобренных жалоб

Опишите проблему более подробно. 
Расхождений не выявлено.

**Comment by mj4444ru** [comment]
это не проблема...  я предлагаю скрывать старые жалобы...  люди меняются...

**Comment by tebaly** [comment]
> Замечания скрываются в общедоступной части через пол года

Прозвучало как _утверждение_

Если нет возражений. Реализуем сейчас.

**Comment by tebaly** [comment]
Вариант:
* установить срок жизни _неактивного_ замечания 3 месяца
* неактивное - пользователи не кликали _я согласен_ (лайк)


Неактивные замечания не удалять
* оно перестанет отображаться в анкета
* в профиле будет отметка _скрыто_

**Comment by tebaly** [comment]
Вообще можно и 60 дней

**Comment by tebaly** [comment]
не. С кэшированием проблема...

Вариант: 
* раз в сутки _отклонять_ все неактивные замечания

**Comment by tebaly** [comment]
Утвердите сроки пожалуйста. Можно будет настроить в любой момент

**Comment by tebaly** [comment]
Реализовано
* скрытие после N (90)
* удаление после  N (90) +M (90)

**Comment by mj4444ru** [comment]
вы меня запутали...  и я сам конечно забыл сказать что это пожелание... 

что значит удалять?  пусть будет скрыто всегда... в случае необходимости можно открыть заново... 
бывает что некорректно одобрять замечание из за текста, но есть похоже отклоненое...

**Comment by tebaly** [comment]
Поздно. Пробуем жить по новой :)

скрытие после 90 дней - три мес (если не кликал никто)
удаление после 180 дней - пол года (оценивается необходимость)
