### ISSUE TITLE
Как быть, если в серых жалобах заметил какое-то нарушение

### ISSUE THREAD

**Issue by Fenslau** [tebaly/freedomsex#93]
например http://sexoo.ru/userinfo/profile/?id=12212330
От @3071926 - Профиль - История - Арбитраж - 1 день назад
Хуй соси ебло конское!

**Comment by tebaly** [comment]
> Как быть

А какие вы рассматриваете варианты?

**Comment by Fenslau** [comment]
В зависимости от содержания. Если например, там что то, что заслуживает блокировки, можно просто блокировать.
А если там допустим, несколько сообщений серых с матом, то можно было бы и наказать. Но сейчас это сделать не представляется возможным так как арбитраж не работает

**Comment by tebaly** [comment]
Для серого отдельный котел #97
