### ISSUE TITLE
возможность отправить на арбитраж случайно пропущенную жалобу

### ISSUE THREAD

**Issue by tebaly** [tebaly/freedomsex#95]
предлагаю сделать в интерфейсе возможность отправить на арбитраж случайно пропущенную жалобу, если вдруг все таки она будет увидена админом.

**Comment by Fenslau** [comment]
http://sexoo.ru/userinfo/profile/5943901/
Целый месяц никто не видел его предложений встретиться за деньги.
Хороший пример

**Comment by Fenslau** [comment]
+ давайте переоткроем тему про серые сообщения, есть кое что важное

**Comment by Fenslau** [comment]
http://sexoo.ru/userinfo/profile/?id=12327647
серых, заслуживающих наказания становится много ))

**Comment by tebaly** [comment]
Вы можете переоткрывать темы не спрашивая разрешения

**Comment by tebaly** [comment]
Теперь можно арбитражить серое

**Comment by tebaly** [comment]
Для серого отдельный котел #97
