### ISSUE TITLE
Глючок с желаниями (извиняюсь если уже было)

### ISSUE THREAD

**Issue by Fenslau** [tebaly/freedomsex#96]
В общем хочет пользователь удалить желания из анкеты, ранее добавленные. Заходит туда и вычеркивает их. И думает, что они уже удалены(на самом деле, с этого момента так и есть). Возвращается к своим делам. Потом решает зайти в свою анкету еще разок и видит, что у него они все еще в списке желанияй якобы. Он думает, блин, я же удалял. Вычеркивает еще раз. Заходит снова - они опять там якобы есть! Хотя уже никому не видны. Бедный пользователь не знает, удалены ли они на самом деле, или он просто что то делает не так, либо просто не работает функция и беспокоится по этому поводу. Все это время, пока он переживает, он видит, что удаленные желания помечаются как совпадающие в анкетах, в которые он заходит.. Через какое то время они и правда удаляются из того списка и больше не подсвечиваются, но вопросы это порождает!

**Comment by tebaly** [comment]
Это еще кто-то видел?)

**Comment by Fenslau** [comment]
Юлии иногда пишут об этом, мол как же их удалить то.

**Comment by tebaly** [comment]
Не знают как. Это же не глюк)) 
* Некоторое время планировалось, чтобы желания максимально разошлись по проекту
* скоро поправим
