### ISSUE TITLE
большой долг капчи

### ISSUE THREAD

**Issue by Fenslau** [tebaly/freedomsex#98]
http://sexoo.ru/userinfo/profile/?id=12341994
http://sexoo.ru/userinfo/profile/?id=12326768
в логах вообще пусто. как такое может быть?

**Comment by tebaly** [comment]
Как это пусто? Кто-то просто игнорирует каптчу

`19.06 ` 06:25 (1) - [ошибки] - кол-во: 12 4678|0
19.06 ` 06:13 (1) - [ошибки] - кол-во: 11 7376|0
19.06 ` 06:11 (1) - [ошибки] - кол-во: 10 9438|0
19.06 ` 06:09 (1) - [ошибки] - кол-во: 9 5246|0
19.06 ` 06:08 (1) - [ошибки] - кол-во: 8 7845|0
19.06 ` 06:06 (1) - [ошибки] - кол-во: 7 3334|0
19.06 ` 04:56 (1) - [ошибки] - кол-во: 6 2560|0
19.06 ` 04:29 (1) - [ошибки] - кол-во: 5 9462|0
19.06 ` 04:28 (1) - [ошибки] - кол-во: 4 9496|0
19.06 ` 03:40 (1) - [ошибки] - кол-во: 4 5434|0
`

**Comment by Fenslau** [comment]
Хмм.. Может быть это спам-боты, которые тестируются на возможность обхода капчи?  А если они это делали ненамеренно...  В логах у 26 летней что-то вообще у меня ничего не отображается....
Получается, может быть такое, что они сразу же, с первого же сообщения, игнорируют какой-то параметр, попадают с первого же сообщения на капчу и просто не вводят ее, а нажимают ок. Может не понимают, что нужно цифры вводить? 
Кстати, интересно конечно: Если анкета новая, то за игнорирование одного параметра сразу попадаешь на капчу. Но вот если Анкетке дня 2-3 и есть уже какой то кредит доверия, то честно говоря трудно на нее попасть. По 1 кредиту за сообщение неподходящее списывается, вне зависимости от того, сколько параметров игнорируется? Причем: Не знаю, почему так. Но у моей тестовой анкеты списывали только за первый факт игнорирования параметра 1 кредитик. Потом можно было писать тому же контакту неограниченное количество сообщений. Тогда как в реале списывается за каждое сообщение, даже одному и тому же контакту. Почему так, не могу понять.

**Comment by tebaly** [comment]
> В логах у 26 летней что-то вообще у меня ничего не отображается....
* там ровно тоже самое
* есть лимит по отображению - 24 часа
* у той что есть соответственно тоже пропадет к утру
* лимит нужен чтобы понимать происходящее в реалтайме
* отображать всё нет возможности
* иногда этот лог имеет значительную длину 
* этот лог до сих пор имеет _техническое назначение_

**Comment by tebaly** [comment]
> [ошибки] - кол-во: 7 3334|0

Выдан код 3334 пришло пустое значение

**Comment by tebaly** [comment]
> Но у моей тестовой анкеты списывали только за первый факт игнорирования параметра 1 кредитик. Потом можно было писать тому же контакту неограниченное количество сообщений. Тогда как в реале списывается за каждое сообщение, даже одному и тому же контакту. Почему так, не могу понять.

#101 далматинец

**Comment by Fenslau** [comment]
Я раньше подозревал, что это либо тесты, либо еще какая то неведомая фигня, но сегодня увидел, что у Юлии спрашивают, мол, что ж такое - долго ли вводить капчу, не могу мол одно сообщение отправить. Тоже новая анкета. Причем он вводит же что-то. Но вообще не то, что просят.

**Comment by tebaly** [comment]
Бывает..
